#!/bin/bash
cd "$(dirname "$0")" || exit 1

name=shipreq/analytics_proxy

docker build -t $name .

case "$1" in
  bash) exec docker run --rm -it $name bash ;;
  run)  exec docker run --rm -p3000:80 $name ;;
  *)    ;;
esac

