# Module enabled in etc/jetty.conf
#--module=logging
-Dorg.eclipse.jetty.util.log.class=org.eclipse.jetty.util.log.Slf4jLog
# Number of days to retain logs
jetty.log.retain=90
# Directory for logging output, either a path relative to ${jetty.base} or an absolute path
jetty.logs=log

