version: '2.4'
services:

  postgres:
    image: postgres:11.3
    container_name: shipreq_dev_postgres
    ports:
      - $PORT_POSTGRES:5432
    environment:
      - POSTGRES_DB=shipreq_dev
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=sqd
    logging:
      driver: none
    cpus: 1
    mem_limit: 400m

  redis:
    image: bitnami/redis:5.0.5
    container_name: shipreq_dev_redis
    ports:
      - $PORT_REDIS:6379
    environment:
      - REDIS_PASSWORD=sqd
    logging:
      driver: none
    mem_limit: 200m

  taskman:
    image: shipreq/taskman
    container_name: shipreq_dev_taskman
    links:
      - postgres
      - logstash
    volumes:
      - ./taskman:/taskman/conf:ro
    environment:
      - db.host=postgres
      - db.database=shipreq_dev
      - db.username=dev
      - db.password=sqd
    cpus: 2
    mem_limit: 448m

  webapp:
    image: shipreq/webapp
    container_name: shipreq_dev_webapp
    links:
      - postgres
      - redis
      - logstash
      - jaeger
    ports:
      - $PORT_SHIPREQ_WEBAPP_HTTP:8080
      - $PORT_SHIPREQ_WEBAPP_HTTPS:8443
      - $PORT_SHIPREQ_WEBAPP_PROMETHEUS:9095
    volumes:
      - ./webapp:/shipreq/conf:ro
    environment:
      - db.host=postgres
      - db.database=shipreq_dev
      - db.username=dev
      - db.password=sqd
      - redis.password=sqd
      - redis.url=redis://redis:6379
      - run.mode=staging
      - shipreq.url=https://localhost:$PORT_SHIPREQ_WEBAPP_HTTPS
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - JAEGER_REPORTER_FLUSH_INTERVAL=2000
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
      - EXTERNAL_PORT_SSL=$PORT_SHIPREQ_WEBAPP_HTTPS
    cpus: 2
    mem_limit: 1856m # 2.25*1024 - 448 for Taskman

  portal:
    image: nginx:1
    container_name: shipreq_dev_portal
    ports:
      - $PORT_PORTAL_HTTP:80
    volumes:
      - ./portal.html:/usr/share/nginx/html/index.html:ro
    cpus: 0.1
    mem_limit: 10m

  prometheus:
    image: prom/prometheus:v2.7.1
    container_name: shipreq_dev_prometheus
    ports:
      - $PORT_PROMETHEUS_HTTP:9090
    extra_hosts:
     - parent-host:$DOCKER0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    cpus: 2
    mem_limit: 100m

  grafana:
    image: grafana/grafana:5.4.3
    container_name: shipreq_dev_grafana
    links:
      - prometheus
    ports:
      - $PORT_GRAFANA_HTTP:3000
    volumes:
      - ./grafana-ds-prometheus.json:/etc/grafana/datasources/prometheus.json
    cpus: 2
    mem_limit: 100m

  # sudo sysctl -w vm.max_map_count=262144
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.0
    container_name: shipreq_dev_elasticsearch
    mem_limit: 1g

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.6.0
    container_name: shipreq_dev_kibana
    links:
      - elasticsearch
    ports:
      - $PORT_KIBANA_HTTP:5601
    logging:
      driver: none
    mem_limit: 200m

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.6.0
    container_name: shipreq_dev_logstash
    links:
      - elasticsearch
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - $PORT_LOGSTASH:14500
    mem_limit: 500m

  # You wouldn't do this in prod - it uses in-memory storage
  jaeger:
    image: jaegertracing/all-in-one:1.11.0
    container_name: shipreq_dev_jaeger
    ports:
      - $PORT_JAEGER_HTTP:16686
      - $PORT_JAEGER_COLLECTOR:14268
    mem_limit: 200m

# Can't get docker to send logs to logstash
# Doesn't work: (https://github.com/moby/moby/issues/20370)
