version: '2'
services:

  postgres:
    image: postgres:9.6.1
    container_name: shipreq_dev_postgres
    ports:
      - $PORT_POSTGRES:5432
    environment:
      - POSTGRES_DB=shipreq_dev
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=sqd
    logging:
      driver: none
    mem_limit: 600m
    cpuset: "0"

  taskman:
    image: shipreq/taskman
    container_name: shipreq_dev_taskman
    links:
      - postgres
      - logstash
    volumes:
      - ./taskman:/taskman/conf:ro
    environment:
      - db.host=postgres
      - db.database=shipreq_dev
      - db.username=dev
      - db.password=sqd
    mem_limit: 448m
    cpuset: "1,2"

  webapp:
    image: shipreq/webapp
    container_name: shipreq_dev_webapp
    links:
      - postgres
      - logstash
    ports:
      - $PORT_SHIPREQ_WEBAPP_HTTP:8080
      - $PORT_SHIPREQ_WEBAPP_HTTPS:8443
    volumes:
      - ./webapp:/shipreq/conf:ro
    environment:
      - db.host=postgres
      - db.database=shipreq_dev
      - db.username=dev
      - db.password=sqd
      - run.mode=staging
      - shipreq.url=https://localhost:$PORT_SHIPREQ_WEBAPP_HTTPS
      - EXTERNAL_PORT_SSL=$PORT_SHIPREQ_WEBAPP_HTTPS
    mem_limit: 1856m # 2.25*1024 - 448 for Taskman
    cpuset: "1,2"

  prometheus:
    image: prom/prometheus:v2.1.0
    container_name: shipreq_dev_prometheus
    ports:
      - $PORT_PROMETHEUS_HTTP:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    # links:
    #   - cadvisor

  grafana:
    image: grafana/grafana:4.6.3
    container_name: shipreq_dev_grafana
    links:
      - prometheus
    ports:
      - $PORT_GRAFANA_HTTP:3000
    volumes:
      - ./grafana-ds-prometheus.json:/etc/grafana/datasources/prometheus.json

#  node-exporter:
#    image: prom/node-exporter
#    container_name: shipreq_dev_nodeexporter
#    volumes:
#      - /proc:/host/proc:ro
#      - /sys:/host/sys:ro
#      - /:/rootfs:ro
#    command:
#      - '--path.procfs=/host/proc'
#      - '--path.sysfs=/host/sys'
#      - --collector.filesystem.ignored-mount-points
#      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
#    ports:
#      - "14102:9100"

  # cadvisor:
  #   image: google/cadvisor
  #   container_name: shipreq_dev_cadvisor
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #   ports:
  #     - "14103:8080"

  # sudo sysctl -w vm.max_map_count=262144
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.2
    container_name: shipreq_dev_elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.1.2
    container_name: shipreq_dev_kibana
    links:
      - elasticsearch
    ports:
      - $PORT_KIBANA_HTTP:5601
    logging:
      driver: none

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.1.2
    container_name: shipreq_dev_logstash
    links:
      - elasticsearch
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - $PORT_LOGSTASH:14500

  # # You wouldn't do this in prod
  # jaeger:
  #   image: jaegertracing/all-in-one:1.2.0
  #   container_name: shipreq_dev_jaeger
  #   ports:
  #     - $PORT_JAEGER_HTTP:16686
  #     - $PORT_JAEGER_COLLECTOR:14268

  # This is what a full Jaeger setup would look like. 1.2.0 only supports ElasticSearch 5 and not 6 though...
  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.2.0
    container_name: shipreq_dev_jaeger_collector
    command: ["/go/bin/collector-linux", "--cassandra.servers=cassandra"] # "--cassandra.keyspace=jaeger"
    ports:
      - "14269"
      - "14268:14268"
      - "14267"
      - "9411:9411"
    environment:
      - SPAN_STORAGE_TYPE=cassandra
    depends_on:
      - cassandra
      - jaeger-cassandra-schema

  jaeger-query:
    image: jaegertracing/jaeger-query:1.2.0
    container_name: shipreq_dev_jaeger_query
    command: ["/go/bin/query-linux", "--query.static-files=/go/jaeger-ui/", "--cassandra.servers=cassandra"] # "--cassandra.keyspace=jaeger"
    ports:
      - "16686:16686"
      - "16687"
    depends_on:
      - cassandra
      - jaeger-cassandra-schema

  cassandra:
    image: cassandra:3.11.1
    container_name: shipreq_dev_cassandra

  jaeger-cassandra-schema:
    image: jaegertracing/jaeger-cassandra-schema:1.2.0
    container_name: shipreq_dev_cassandra_schema
    depends_on:
      - cassandra


# TODO influxDB (?) (for Prometheus)
# TODO alertmanager
# TODO postgres metrics

  portal:
    image: nginx:1
    container_name: shipreq_dev_portal
    ports:
      - $PORT_PORTAL_HTTP:80
    volumes:
      - ./portal.html:/usr/share/nginx/html/index.html:ro


# Can't get docker to send logs to logstash
# Doesn't work: (https://github.com/moby/moby/issues/20370)
