akka {
  loggers = ["akka.event.slf4j.Slf4jLogger"]
  loglevel = "DEBUG"

  actor.deployment {
    /manager/router {
      router = balancing-pool
      nr-of-instances = 16
      pool-dispatcher {
        fork-join-executor {
          parallelism-min = 2
          parallelism-factor = 3.0
          parallelism-max = 16
        }
      }
    }
  }
}

manager.poll = 40 seconds

dedicated {
  type = PinnedDispatcher
  executor = "thread-pool-executor"
}
