version: '2.4'

volumes:
  data-prometheus:

services:

  postgres:
    image: shipreq/dev/postgres
    container_name: shipreq_dev_postgres
    ports:
      - $PORT_POSTGRES:5432
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    logging:
      driver: none
    cpus: 1
    mem_limit: 400m

  redis:
    image: bitnami/redis:5.0.5
    container_name: shipreq_dev_redis
    ports:
      - $PORT_REDIS:6379
    environment:
      - REDIS_PASSWORD=sqd
    logging:
      driver: none
    mem_limit: 200m

  taskman:
    image: shipreq/taskman
    container_name: shipreq_dev_taskman
    links:
      - postgres
    volumes:
      - ./taskman:/taskman/conf:ro
    environment:
      - db.host=postgres
      - db.database=$POSTGRES_DB
      - db.username=$POSTGRES_USER
      - db.password=$POSTGRES_PASSWORD
      - LOG_LEVEL_ROOT=INFO
      - LOG_LEVEL_SHIPREQ=DEBUG
    cpus: 2
    mem_limit: 300m

  webapp:
    image: shipreq/webapp
    container_name: shipreq_dev_webapp
    links:
      - postgres
      - redis
      - fake_cdn
    ports:
      - $PORT_SHIPREQ_WEBAPP:8080
    volumes:
      - ./webapp:/mnt/import:ro
    environment:
      - db.host=postgres
      - db.database=$POSTGRES_DB
      - db.username=$POSTGRES_USER
      - db.password=$POSTGRES_PASSWORD
      - redis.password=sqd
      - redis.url=redis://redis:6379
      - run.mode=staging
      - shipreq.analytics_proxy.url=http://localhost:$PORT_ANALYTICS_PROXY
      - shipreq.staticAssetCdn=http://localhost:$PORT_FAKE_CDN
      - shipreq.url=http://localhost:$PORT_SHIPREQ_WEBAPP
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - JAEGER_REPORTER_FLUSH_INTERVAL=2000
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
      - IMPORT_VOL=/mnt/import
      - LOG_LEVEL_ROOT=INFO
      - LOG_LEVEL_SHIPREQ=DEBUG
    cpus: 2
    mem_limit: 1856m # 2.25*1024 - 448 for Taskman
    mem_reservation: 800m
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/ops/ok || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

  fake_cdn:
    image: shipreq/dev/fake_cdn
    container_name: shipreq_dev_fake_cdn
    environment:
      - TARGET=http://webapp:8080
    ports:
      - $PORT_FAKE_CDN:6666
    cpus: 2
    mem_limit: 64m

  analytics_proxy:
    image: shipreq/analytics_proxy
    container_name: shipreq_dev_analytics_proxy
    ports:
      - $PORT_ANALYTICS_PROXY:80
    cpus: 2
    mem_limit: 64m

  ##################################################################################################
  # DevOps: Metrics

  node_exporter:
    image: shipreq/ops/node_exporter
    container_name: shipreq_dev_node_exporter
    network_mode: host
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    command:
      - '--path.rootfs=/rootfs'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
    mem_limit: 100m
    restart: unless-stopped

  cadvisor:
    image: shipreq/ops/cadvisor
    container_name: shipreq_dev_cadvisor
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /dev/disk/:/dev/disk:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run:/var/run:ro
    mem_limit: 128m
    restart: unless-stopped

  postgres_exporter:
    image: shipreq/ops/postgres_exporter
    container_name: shipreq_dev_postgres_exporter
    ports:
      - $PORT_POSTGRES_EXPORTER:9187
    links:
      - postgres
    environment:
      - DATA_SOURCE_NAME=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB?sslmode=disable

  # This locally fakes what you'd get with the real ecs_exporter running in AWS ECS
  ecs_exporter:
    image: nginx:1
    container_name: shipreq_dev_ecs_exporter
    ports:
      - $PORT_ECS_EXPORTER:80
    volumes:
      - ./ecs_exporter.metrics.txt:/usr/share/nginx/html/metrics:ro
    cpus: 0.1
    mem_limit: 10m

  prometheus-tech:
    image: shipreq/ops/prometheus-tech
    container_name: shipreq_dev_prometheus-tech
    user: root
    extra_hosts:
      - parent-host:$DOCKER0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - data-prometheus:/data
    environment:
      - EXTERNAL_URL=http://prometheus-tech:9090/prometheus/tech/
    command:
      - --storage.tsdb.retention.time=730d
    cpus: 2
    mem_limit: 200m

  grafana:
    image: shipreq/ops/grafana
    container_name: shipreq_dev_grafana
    links:
      - prometheus-tech
    environment:
      - PROMETHEUS_TECH_URL=http://prometheus-tech:9090/prometheus/tech
      - PROMETHEUS_BIZ_URL=http://todo
      - PROMETHEUS_TECH_SCRAPE_INTERVAL=20s
      - PROMETHEUS_BIZ_SCRAPE_INTERVAL=2m
    cpus: 2
    mem_limit: 100m

  ##################################################################################################
  # DevOps: Logging

  filebeat:
    image: shipreq/ops/filebeat
    container_name: shipreq_dev_filebeat
    links:
      - elasticsearch
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log:/host/var/log:ro
    environment:
      - AWS_INSTANCE_ID=i-local
      - AWS_INSTANCE_IP=127.0.0.1
      - CLUSTER=local
      - ES_HOSTS=elasticsearch:9200
    command:
      - -e
      - -strict.perms=false
      - -d
      - "processors"
    mem_limit: 100m

  # sudo sysctl -w vm.max_map_count=262144
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.7.0
    container_name: shipreq_dev_elasticsearch
    environment:
      - discovery.type=single-node
    mem_limit: 1g

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.7.0
    container_name: shipreq_dev_kibana
    links:
      - elasticsearch
    environment:
      - SERVER_BASEPATH=/_plugin/kibana
      - SERVER_REWRITEBASEPATH=true
    mem_limit: 1g

  ##################################################################################################
  # DevOps: Other

  portal:
    image: shipreq/ops/portal
    container_name: shipreq_dev_portal
    ports:
      - $PORT_PORTAL:80
    environment:
      - CADVISOR_URL=http://cadvisor:8080
      - DNS_TTL=10s
      - FRESHDESK_DOMAIN=yoarmum
      - GA_TRACKING_ID=UA-105581783-2
      - GRAFANA_URL=http://grafana:3000
      - JAEGER_URL=http://localhost:$PORT_JAEGER_HTTP
      - KIBANA_DEFAULT_PATH=
      - KIBANA_URL=http://kibana:5601
      - PROMETHEUS_BIZ_URL=http://todo
      - PROMETHEUS_TECH_URL=http://prometheus-tech:9090
      - SHIPREQ_ENV=local-dev
      - SHIPREQ_URL=http://localhost:$PORT_SHIPREQ_WEBAPP
    cpus: 0.1
    mem_limit: 400m

  # You wouldn't do this in prod - it uses in-memory storage
  jaeger:
    image: jaegertracing/all-in-one:1.15.1
    container_name: shipreq_dev_jaeger
    ports:
      - $PORT_JAEGER_HTTP:16686
      - $PORT_JAEGER_COLLECTOR:14268
    mem_limit: 200m
