global:
  scrape_interval: 5s

scrape_configs:

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
    relabel_configs:
      - source_labels: [__address__]
        regex: ".*"
        replacement: '127.0.0.1'
        target_label: instance

  - job_name: 'cadvisor'
    metrics_path: '/cadvisor/metrics'
    static_configs:
      - targets: ['cadvisor:8080']
    relabel_configs:
      - source_labels: [__address__]
        regex: ".*"
        replacement: '127.0.0.1'
        target_label: instance
    metric_relabel_configs:
      # Drop metrics
      - source_labels: [__name__]
        regex: 'container_tasks_state'
        action: drop
      - source_labels: ['container_label_com_docker_compose_project']
        regex: 'shipreqdev'
        action: keep
      # Fake ECS attributes
      - source_labels: ['container_label_com_docker_compose_service']
        target_label: ecs_name
      - source_labels: ['container_label_com_docker_compose_service']
        target_label: ecs_taskdef_name
      - source_labels: ['container_label_com_docker_compose_service']
        action: replace
        regex: '.+'
        replacement: '1'
        target_label: ecs_taskdef_ver
      - source_labels: ['container_label_com_docker_compose_service']
        action: replace
        regex: '.+'
        replacement: 'local-dev'
        target_label: ecs_cluster
      # Drop labels
      - regex: 'container_label_.*'
        action: labeldrop

  - job_name: 'ecs_exporter'
    # scrape_interval: 1m
    static_configs:
      - targets: ['ecs_exporter:80']

  - job_name: 'prometheus-tech'
    metrics_path: '/prometheus/tech/metrics'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'webapp-dev'
    metrics_path: '/ops/metrics'
    static_configs:
      - targets: ['webapp:8080']

  - job_name: 'taskman-dev'
    static_configs:
      - targets: ['taskman:9031']

  - job_name: 'webapp-local'
    metrics_path: '/ops/metrics'
    static_configs:
      - targets: ['parent-host:8080']

  - job_name: 'taskman-local'
    static_configs:
      - targets: ['parent-host:9031']

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']
    metric_relabel_configs:
    # Drop most tech metrics; only really keeping scaping metrics
    - source_labels: [__name__]
      regex: '^(go|process|postgres)_.*'
      action: drop
    # Drop unnecessary labels
    - regex: 'server|instance'
      action: labeldrop
