global:
  scrape_interval: 5s

scrape_configs:

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
    relabel_configs:
      - source_labels: [__address__]
        regex: "([^:]+):\\d+"
        target_label: instance

  - job_name: 'cadvisor'
    metrics_path: '/cadvisor/metrics'
    static_configs:
      - targets: ['cadvisor:8080']
    relabel_configs:
      - source_labels: [__address__]
        regex: "([^:]+):\\d+"
        target_label: instance

  - job_name: 'prometheus-tech'
    metrics_path: '/prometheus/tech/metrics'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'webapp-dev'
    metrics_path: '/ops/metrics'
    static_configs:
      - targets: ['webapp:8080']

  - job_name: 'taskman-dev'
    static_configs:
      - targets: ['taskman:9031']

  - job_name: 'webapp-local'
    metrics_path: '/ops/metrics'
    static_configs:
      - targets: ['parent-host:8080']

  - job_name: 'taskman-local'
    static_configs:
      - targets: ['parent-host:9031']

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']
