#!/bin/bash
cd "$(dirname "$(readlink -e "$0")")" || exit 1
[ -z "$GCP_PROJECT" ] && echo "Use ./target to target an environment first." && exit 1

gcloud="gcloud --project $GCP_PROJECT"

VERB=create
$gcloud deployment-manager deployments describe "$INFRA_NAME" &>/dev/null
[ $? -eq 0 ] && VERB=update

set -e

y=$ENVTMP/infra.yml
echo "
imports:
- path: infra-db.jinja
- path: infra-cluster.jinja

resources:
- name: cluster
  type: infra-cluster.jinja
  properties:
    GCP_ZONE: $GCP_ZONE
    CLUSTER_NAME: $CLUSTER_NAME
- name: db
  type: infra-db.jinja
  properties:
    GCP_REGION: $GCP_REGION
    GCP_ZONE: $GCP_ZONE
    DB_INSTANCE: $DB_INSTANCE
" > $y

cp -f infra*.jinja $ENVTMP

exec $gcloud deployment-manager deployments $VERB "$INFRA_NAME" --config $y "$@"
