user nginx;
worker_processes 1;

error_log /var/log/nginx/error.log warn;

pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {

  include /etc/nginx/mime.types;
  gzip on;
  log_format main  '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';
  access_log /var/log/nginx/access.log  main;
  sendfile on;
  keepalive_timeout 65;

  server {

    location / {
      root   /usr/share/nginx/html;
      index  index.html;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
      root   /usr/share/nginx/html;
    }

    # Below instead of just
    #
    #   proxy_pass URL
    #
    # I'm doing this
    #
    #   set $BLAH ...
    #   proxy_pass $BLAH ...
    #
    # This prevents nginx doing a static resolution at startup and instead
    # allows it to dynamically resolve the address on each request.

    resolver ${DNS_IP} valid=${DNS_TTL};

    location ~ ^/(_plugin/kibana/.*)$ {
      set $root ${KIBANA_URL};
      proxy_pass $root/$1$is_args$args;
      proxy_http_version 1.1;
    }

    location ~ ^/(cadvisor/.*)$ {
      set $root ${CADVISOR_URL};
      proxy_pass $root/$1$is_args$args;
      proxy_http_version 1.1;
    }

    location ~ ^/(prometheus/tech/.*)$ {
      set $root ${PROMETHEUS_TECH_URL};
      proxy_pass $root/$1$is_args$args;
      proxy_http_version 1.1;
    }

    location ~ ^/(prometheus/biz/.*)$ {
      set $root ${PROMETHEUS_BIZ_URL};
      proxy_pass $root/$1$is_args$args;
      proxy_http_version 1.1;
    }

    location ~ ^/(grafana/.*)$ {
      set $root ${GRAFANA_URL};
      proxy_pass $root/$1$is_args$args;
      proxy_http_version 1.1;
    }
  }
}
