# Module enabled in etc/jetty.conf
#--module=logging
-Dorg.eclipse.jetty.util.log.class=org.eclipse.jetty.util.log.Slf4jLog
# Number of days to retain logs
jetty.log.retain=90
# Directory for logging output, either a path relative to ${jetty.base} or an absolute path
jetty.logs=log


## Request Log Configuration
--module=requestlog
# How many days to retain the logs
requestlog.retain=90
# If an existing log with the same name is found, just append to it
requestlog.append=true
# Use the extended log output
requestlog.extended=true
# Log http cookie information as well
requestlog.cookies=false
# Set the log output timezone
requestlog.timezone=Australia/Sydney

