[main]

# Hashing settings
cm = org.apache.shiro.authc.credential.HashedCredentialsMatcher
cm.hashAlgorithmName = SHA-512
cm.hashIterations = 1007
cm.storedCredentialsHexEncoded = false

# Use custom realm (so that credentials are checked against the DB)
realm = com.beardedlogic.usecase.security.AppSecurityRealm
realm.credentialsMatcher = $cm
