version = 2.7.5

assumeStandardLibraryStripMargin = true
align.stripMargin                = true

# continuationIndent.caseSite = 5
indentOperator.topLevelOnly = false
align.preset = most
align.arrowEnumeratorGenerator = true
align.openParenDefnSite = true


maxColumn           = 120
# project.git         = true
# indentOperator      = spray

spaces.inImportCurlyBraces       = false

trailingCommas = always

rewrite.rules = [
  AvoidInfix,
  RedundantBraces,
  RedundantParens,
  PreferCurlyFors
]

align.tokens.add = [
  {code = ":", owner = "Defn.(Va[lr]|Def)|Term.Param"},
]