version: 0.2

phases:
  pre_build:
    commands:
      - cd Code
      - export JAVA_OPTS="-Xss2m"
  build:
    commands:
      - >
        /bin/bash -c 'set -o pipefail;
        sbt
        test
        | strip-ansi'
    finally:
      - find /root/.cache/coursier /root/.ivy2 /root/.sbt -name '*.lock' -type f -exec rm -fv {} +

cache:
  paths:
    - '/root/.cache/coursier/**/*'
    - '/root/.ivy2/**/*'
    - '/root/.sbt/**/*'
