version: 0.2

phases:
  pre_build:
    commands:
      - cd Code
      - nohup dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
      - docker pull $DEV_POSTGRES_IMAGE_URL
      - docker pull $WEBAPP_IMAGE_URL:latest || true
      - docker pull $TASKMAN_IMAGE_URL:latest || true
      - timeout 15 sh -c "until docker info; do sleep .5; done"
      - bin/env test --no-ansi up -d
  build:
    commands:
      - >
        /bin/bash -c '
          set -o pipefail;
          export CI=1;
          export MODE=release;
          SBT="sbt -Dsbt.server.autostart=false -no-colors -J-Xmx12g";
          $SBT clean test | strip-ansi && \
          $SBT taskman-server/docker     webapp-server/docker \
               taskman-server/dockerPush webapp-server/dockerPush \
             | strip-ansi
        '
    finally:
      - find /root/.cache/coursier /root/.ivy2 /root/.sbt -name '*.lock' -type f -exec rm -fv {} +
      - bin/env test --no-ansi down

cache:
  paths:
    - '/root/.cache/coursier/**/*'
