#!/bin/bash
#cd "$(dirname "$0")"
#[ -z "$1" ] && echo "Usage: $0 <xxx>" && exit 1
#tmp=/tmp/$(date +%Y%m%d-%H%M%S)-$$
#xxx="$(cd "$(dirname "$0")/xxx" && pwd)"

url=https://us8.api.mailchimp.com/2.0
key=d96852e88497f5dd2d19da53fc565236-us8

# Get campaigns
#req='{"apikey":"'$key'"}'
#curl -X POST -H "Content-Type: application/json" -d "$req" $url/campaigns/list.json

#req='{"apikey":"'$key'","id":"270dff4105"
#  ,"double_optin":false
#  ,"update_existing":true
#  ,"send_welcome":false
#  ,"batch": [{
#    "email": {"email": "great@yay.com"}
#    ,"merge_vars": {
#      "NAME":"Awesomeness!"
#      ,"NEWSLETTER": 1
#      ,"ACCT":"Active"
#    }
#  }]
#}'
#echo $(curl -X POST -H "Content-Type: application/json" -d "$req" $url/lists/batch-subscribe.json) #| json_reformat

#req='{"apikey":"'$key'","id":"270dff4105"
#  ,"double_optin":true
#  ,"update_existing":false
#  ,"send_welcome":false
#  ,"email": {"email": "japgolly+t1@gmail.com"}
#  ,"merge_vars": {
#    "NAME":"Name change!"
#    ,"NEWSLETTER": 1
#    ,"ACCT":"Active"
#  }
#}'
#echo $(curl -X POST -H "Content-Type: application/json" -d "$req" $url/lists/subscribe.json) #| json_reformat

req='{"apikey":"'$key'","id":"270dff4105"
  ,"email": {"email": "japgolly+t1@gmail.com"}
  ,"merge_vars": {
    "NAME":"Name change!"
    ,"NEWSLETTER": 1
    ,"ACCT":"Active"
  }
}'
echo $(curl -X POST -H "Content-Type: application/json" -d "$req" $url/lists/update-member) #| json_reformat

# Get email addresses
#cid=5901d4387f
#req='{"apikey":"'$key'","cid":"'$cid'","opts":{"start":0,"limit":100}}'
#echo "$req"
#curl -X POST -H "Content-Type: application/json" -d "$req" $url/reports/sent-to.json | json_reformat

