addCommandAlias("testJVM", ""
  + ";baseUtilJVM/test"
  + ";baseTestJVM/test"
  + ";taskmanApiLogic/test"
  + ";taskmanApi/test"
  + ";taskmanServerLogic/test"
  + ";taskmanServer/test"
  + ";webappBaseTestJVM/test"
  + ";webappMemberTestJVM/test"
  + ";webappClientPublicJVM/test"
  + ";webappServerLogicJVM/test"
  + ";webappServer/test"
)

addCommandAlias("testJS", ""
  + ";baseUtilJS/test"
  + ";baseTestJS/test"
  + ";webappBaseTestJS/test"
  + ";webappMemberTestJS/test"
  + ";webappClientHome/test"
  + ";webappClientPublicJS/test"
  + ";webappClientWw/test"
  + ";webappClientProject/test"
  + ";webappServerLogicJS/test"
)
