addCommandAlias("testJVM", ""
  + ";baseUtilJVM/testOnly * -- --report-slowest"
  + ";baseTestJVM/testOnly * -- --report-slowest"
  + ";taskmanApiLogic/testOnly * -- --report-slowest"
  + ";taskmanApi/testOnly * -- --report-slowest"
  + ";taskmanServerLogic/testOnly * -- --report-slowest"
  + ";taskmanServer/testOnly * -- --report-slowest"
  + ";webappBaseTestJVM/testOnly * -- --report-slowest"
  + ";webappMemberTestJVM/testOnly * -- --report-slowest"
  + ";webappClientPublicJVM/testOnly * -- --report-slowest"
  + ";webappServerLogicJVM/testOnly * -- --report-slowest"
  + ";webappServer/testOnly * -- --report-slowest"
)

addCommandAlias("testJS", ""
  + ";baseUtilJS/testOnly * -- --report-slowest"
  + ";baseTestJS/testOnly * -- --report-slowest"
  + ";webappBaseTestJS/testOnly * -- --report-slowest"
  + ";webappMemberTestJS/testOnly * -- --report-slowest"
  + ";webappClientHome/testOnly * -- --report-slowest"
  + ";webappClientPublicJS/testOnly * -- --report-slowest"
  + ";webappClientWw/testOnly * -- --report-slowest"
  + ";webappClientProject/testOnly * -- --report-slowest"
  + ";webappServerLogicJS/testOnly * -- --report-slowest"
)
