#!/bin/bash
cd "$(dirname "$0")"
j=/tmp/jetty-dist
if [ ! -e "$j" ]; then
  ver="$(fgrep org.eclipse.jetty ../../../../project/Dependencies.scala | perl -pe 's/^.+?([\d.]+\.v\d{8}).+$/$1/')"
  src=~/.coursier/cache/v1/https/repo1.maven.org/maven2/org/eclipse/jetty/jetty-distribution/$ver/jetty-distribution-$ver.tar.gz
  [ ! -e "$src" ] && echo "File not found: $src" && exit 1
  tar xzf "$src"
  mv jetty-distribution-$ver "$j"
fi
java -cp "$j"/lib/jetty-util-*.jar org.eclipse.jetty.util.security.Password "$@"
echo
