#!/bin/bash
cd "$(dirname "$(readlink -e "$0")")" || exit 1

S=shipreq-prototype

tmux -2 new-session -d -s $S \
  && tmux rename-window ctl \
  && tmux split-window -v \
  && tmux select-pane -t 1 && tmux resize-pane -D 999 && tmux resize-pane -U 4 \
  && tmux send-keys "clear; grunt watch" C-m \
  && tmux select-pane -t 0 \
  && tmux send-keys "vim prototype.haml" C-m

tmux -2 attach-session -t $S

