#!/bin/sh

[ -z "$CONFIG" ] && echo '$CONFIG is blank!' && exit 1

echo "$CONFIG" > /etc/prometheus/prometheus.yml

echo "----------------------------------------------------------------------------"
cat /etc/prometheus/prometheus.yml
echo "----------------------------------------------------------------------------"

CMD=/bin/prometheus
CMD="$CMD --web.listen-address=0.0.0.0:9091"
CMD="$CMD --config.file=/etc/prometheus/prometheus.yml"
CMD="$CMD --storage.tsdb.path=/data/"
CMD="$CMD --web.external-url=http://prometheus:9091/prometheus/biz/"

echo "> $CMD $@"
exec $CMD "$@"