apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: taskman
  # labels:
    # app: taskman
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: taskman
    spec:
      containers:
      - name: taskman
        image: "asia.gcr.io/shipreq-dev/taskman:latest"
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "0.5"
            memory: "365Mi"
          limits:
            cpu: "1"
            memory: "448Mi"
        volumeMounts:
        - name: taskman-props
          mountPath: /taskman/conf
        - name: taskman-secrets
          mountPath: /taskman/secrets
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.09
        command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                  "-instances=shipreq-dev:australia-southeast1:shipreq-db=tcp:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
          - name: ssl-certs
            mountPath: /etc/ssl/certs
          - name: cloudsql
            mountPath: /cloudsql
      volumes:
      - name: taskman-props
        configMap:
          name: taskman-props
      - name: taskman-secrets
        secret:
          secretName: taskman-secrets
      - name: cloudsql-instance-credentials
        secret:
          secretName: taskman-credentials
      - name: ssl-certs
        hostPath:
          path: /etc/ssl/certs
      - name: cloudsql
        emptyDir:
      restartPolicy: Always
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: taskman-props
  labels:
    name: taskman-props
    # app: taskman
data:
  logback.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration
      xmlns="http://ch.qos.logback/xml/ns/logback"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://ch.qos.logback/xml/ns/logback http://ch.qos.logback/xml/ns/logback/logback.xsd">

      <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder class="ch.qos.logback.classic.encoder.PatternLayoutEncoder">
          <pattern>%d{HH:mm:ss.SSS} %-5level [%-32logger{32}] {%-10X{who}} %msg%n</pattern>
        </encoder>
        <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
          <level>DEBUG</level>
        </filter>
      </appender>

      <logger name="akka.event.EventStream" level="WARN" />
      <logger name="akka.event.slf4j" level="WARN" />
      <logger name="shipreq" level="DEBUG" />

      <root level="INFO">
        <appender-ref ref="STDOUT" />
      </root>
    </configuration>
  shipreq.properties: |
    db.appname                         = TASKMAN
    db.schema                          = taskman
    db.pool.maximumPoolSize            = 8

    freshdesk.domain                   = yoarmum
    freshdesk.key                      = 6nOvQN6fH4XKlVCbXHD9
    freshdesk.taskmanEmail             = Taskman <taskman@shipreq.com>
    freshdesk.org.landingPage          = Sales / Lead
    freshdesk.org.failure              = QA / Incident
    freshdesk.logLevel                 = trace

    # Ensure [Allow less secure apps] is enabled in Gmail
    # https://support.google.com/accounts/answer/6010255
    mail.smtp.host                     = smtp.gmail.com
    mail.smtp.socketFactory.port       = 465
    mail.smtp.socketFactory.class      = javax.net.ssl.SSLSocketFactory
    mail.smtp.ssl.enable               = true
    mail.smtp.auth                     = true
    mail.smtp.port                     = 465
    mail.user                          = yoar.mum@gmail.com
    mail.password                      = 6vJDhVXYm8G95uXj3gPq
    mail.concurrency.max               = 4
    mail.public.from                   = default@props.com
    mail.archive.to                    = japgolly+test_taskman_archive@gmail.com

    mailchimp.dc                       = us8
    mailchimp.key                      = d96852e88497f5dd2d19da53fc565236-us8
    mailchimp.masterList               = Master
    mailchimp.logLevel                 = trace

    shipreq.schema                     = public

    taskman.poll.every                 = 5 sec
    taskman.poll.gap                   = 1 sec
    taskman.queueSize                  = 10
    taskman.remoteCfg.retry.delay      = 3 sec
    taskman.trustPeriod                = 1 min
