#!/bin/bash
cd "$(dirname "$(readlink -e "$0")")" || exit 1
# [ $# -ne 1 ] && echo "Usage: $0 <xxx>" && exit 1
# tmp=/tmp/$(date +%Y%m%d-%H%M%S)-$$

DEP=shipreq-dev
VERB=create
gcloud deployment-manager deployments describe $DEP &>/dev/null
[ $? -eq 0 ] && VERB=update
echo "> gcloud deployment-manager deployments $VERB $DEP --config infra-dev.yml"
gcloud deployment-manager deployments $VERB $DEP --config infra-dev.yml
