package shipreq.webapp.base.data

import japgolly.microlibs.stdlib_ext.StdlibExt._
import java.time.Instant
import nyaya.prop.Prop
import scala.annotation.elidable
import shipreq.base.util.univeq._
import shipreq.webapp.base.event._

/**
  * @param eventsInit Initial events generated by ShipReq at project creation.
  */
final case class ProjectMetaData(id           : ProjectId.Public,
                                 name         : Project.Name,
                                 eventsInit   : Int,
                                 eventsTotal  : Int,
                                 reqsLive     : Int,
                                 reqsTotal    : Int,
                                 createdAt    : Instant,
                                 accessedAt   : Instant,
                                 lastUpdatedAt: Option[Instant]) {

  def latestOrd: Option[EventOrd.Latest] =
    Option.when(eventsTotal > 0)(EventOrd.Latest(eventsTotal))

  def eventsPostInit =
    eventsTotal - eventsInit

  def lastUpdatedOrCreatedAt: Instant =
    lastUpdatedAt.getOrElse(createdAt)

  @elidable(elidable.ASSERTION)
  def assertInSyncWith(p: => Project): Unit =
    ProjectMetaData.props(p) assert this

  def applyEvent(ve: VerifiedEvent, newProject: Project, when: Instant): ProjectMetaData =
    applyEvents(ve :: Nil, newProject, when)

  def applyEvents(ves: IterableOnce[VerifiedEvent], newProject: Project, when: Instant): ProjectMetaData =
    ProjectMetaData.fromProject(newProject)(
      id            = id,
      eventsInit    = eventsInit,
      eventsTotal   = eventsTotal + ves.size,
      createdAt     = createdAt,
      accessedAt    = when,
      lastUpdatedAt = Some(when))
}

object ProjectMetaData {
  implicit def equality: UnivEq[ProjectMetaData] = UnivEq.derive

  def fromProject(p            : Project)
                 (id           : ProjectId.Public,
                  eventsInit   : Int,
                  eventsTotal  : Int,
                  createdAt    : Instant,
                  accessedAt   : Instant,
                  lastUpdatedAt: Option[Instant]): ProjectMetaData =
    ProjectMetaData(
      id            = id,
      name          = p.name,
      eventsInit    = eventsInit,
      eventsTotal   = eventsTotal,
      reqsLive      = p.liveReqCount,
      reqsTotal     = p.content.reqs.size,
      createdAt     = createdAt,
      accessedAt    = accessedAt,
      lastUpdatedAt = lastUpdatedAt)

  def props(project: Project): Prop[ProjectMetaData] = {
    type P = ProjectMetaData
    Prop.equal[P]("Project name")(_.name, _ => project.name) &
      Prop.equal[P]("Total reqs")(_.reqsTotal, _ => project.content.reqs.size) &
      Prop.equal[P]("Live reqs")(_.reqsLive, _ => project.liveReqCount)
  }
}