package shipreq.webapp.base.data

import japgolly.microlibs.stdlib_ext.StdlibExt._
import java.time.Instant
import nyaya.prop.Prop
import scala.annotation.elidable
import shipreq.base.util.univeq._
import shipreq.webapp.base.event.EventOrd

/**
  * @param initEventCount Initial events generated by ShipReq at project creation.
  */
final case class ProjectMetaData(id             : ProjectId.Public,
                                 name           : Project.Name,
                                 initEventCount : Int,
                                 totalEventCount: Int,
                                 reqCount       : Int,
                                 createdAt      : Instant,
                                 lastUpdatedAt  : Option[Instant]) {

  def latestOrd: Option[EventOrd.Latest] =
    Option.when(totalEventCount > 0)(EventOrd.Latest(totalEventCount))

  def nonInitEventCount =
    totalEventCount - initEventCount

  def lastUpdatedOrCreatedAt: Instant =
    lastUpdatedAt.getOrElse(createdAt)

  @elidable(elidable.ASSERTION)
  def assertInSyncWith(p: => Project): Unit =
    ProjectMetaData.props(p) assert this

  import shipreq.webapp.base.event._

  def applyEvent(ve: VerifiedEvent, when: Instant): ProjectMetaData = {
    var newName     = name
    var newReqCount = reqCount
    ve.event match {
      case e if Event.reqCreationEventFilter(e) => newReqCount += 1
      case e: Event.ProjectNameSet              => newName = e.name
      case _                                    => ()
    }
    copy(
      name            = newName,
      totalEventCount = totalEventCount + 1,
      reqCount        = newReqCount,
      lastUpdatedAt   = Some(when))
  }

  def applyEvents(ve: TraversableOnce[VerifiedEvent], when: Instant): ProjectMetaData =
    ve.foldLeft(this)(_.applyEvent(_, when))
}

object ProjectMetaData {
  implicit def equality: UnivEq[ProjectMetaData] = UnivEq.derive

  def props(project: Project): Prop[ProjectMetaData] = {
    type P = ProjectMetaData
    Prop.equal[P]("Project name")(_.name, _ => project.name) &
      Prop.equal[P]("Req count")(_.reqCount, _ => project.content.reqs.size)
  }
}