#!/bin/bash

function dir {
  echo
  echo "$1"
  ls -l "$1" | fgrep -i semant
}

clear
cd "$(dirname "$(readlink -e "$0")")" || exit 1

./json5 -c semantic.json5 && \
  cd semantic && ../gulp build && cd .. && \
  echo && ./gulp ws:vendor

dir ../webapp-server/src/main/webapp/dev
dir ../webapp-server/src/main/webapp/a
