global:
  scrape_interval: ${PROMETHEUS_TECH_SCRAPE_INTERVAL}

scrape_configs:

  ##########################################################################
  # Common daemons

  - job_name: 'node_exporter'
    dns_sd_configs:
      - names: [ '${APP_HOST}', '${OPS_HOST}' ]
        type: 'A'
        port: ${NODE_EXPORTER_PORT}
    static_configs:
      - targets: ['${NAT_HOST}:${NODE_EXPORTER_PORT}']
    relabel_configs:
      # Remove port from instance
      - source_labels: [__address__]
        regex: "([^:]+):\\d+"
        target_label: instance

  - job_name: 'cadvisor'
    metrics_path: '${CADVISOR_PATH}/metrics'
    dns_sd_configs:
      - names: [ '${APP_HOST}', '${OPS_HOST}' ]
        type: 'A'
        port: ${CADVISOR_PORT}
    static_configs:
      - targets: ['${NAT_HOST}:${CADVISOR_PORT}']
    relabel_configs:
      # Remove port from instance
      - source_labels: [__address__]
        regex: "([^:]+):\\d+"
        target_label: instance
    metric_relabel_configs:
    # Drop metrics
    - source_labels: [__name__]
      regex: 'container_tasks_state'
      action: drop
    # Rename ECS attributes
    - source_labels: ['container_label_com_amazonaws_ecs_cluster']
      target_label: ecs_cluster
    - source_labels: ['container_label_com_amazonaws_ecs_container_name']
      target_label: ecs_name
    - source_labels: ['container_label_com_amazonaws_ecs_task_definition_family']
      target_label: ecs_taskdef_name
    - source_labels: ['container_label_com_amazonaws_ecs_task_definition_version']
      target_label: ecs_taskdef_ver
    # Drop labels
    - regex: 'container_label_.*'
      action: labeldrop

  ##########################################################################
  # NAT

  - job_name: 'squid_exporter'
    static_configs:
      - targets: ['${NAT_HOST}:${SQUID_EXPORTER_PORT}']

  ##########################################################################
  # Ops cluster

  - job_name: 'ecs_exporter'
    scrape_interval: ${ECS_EXPORTER_SCRAPE_INTERVAL}
    dns_sd_configs:
      - names: [ '${OPS_HOST}' ]
        type: 'A'
        port: ${ECS_EXPORTER_PORT}

  - job_name: 'prometheus-tech'
    metrics_path: '${PROMETHEUS_TECH_PATH}/metrics'
    dns_sd_configs:
      - names: [ '${PROMETHEUS_TECH_HOST}' ]
        type: 'A'
        port: ${PROMETHEUS_TECH_PORT}

  - job_name: 'prometheus-biz'
    metrics_path: '${PROMETHEUS_BIZ_PATH}/metrics'
    dns_sd_configs:
      - names: [ '${PROMETHEUS_BIZ_HOST}' ]
        type: 'A'
        port: ${PROMETHEUS_BIZ_PORT}

  ##########################################################################
  # App cluster

  - job_name: 'shipreq-taskman'
    dns_sd_configs:
      - names: [ '${APP_HOST}' ]
        type: 'A'
        port: ${SHIPREQ_TASKMAN_PORT}

  - job_name: 'shipreq-webapp'
    metrics_path: '/ops/metrics'
    dns_sd_configs:
      - names: [ '${SHIPREQ_WEBAPP_SD_DOMAIN}' ]
        type: 'SRV'
