#!/bin/bash

export http_proxy=http://127.0.0.1:3128
export https_proxy=http://127.0.0.1:3128

function testGet {
  echo "======================== $1 ========================"
  http -h --timeout 2 --max-redirects 30 "$1"
  # curl -v "$1" -s -o /dev/null
}

function runTests {
  clear
  testGet http://amazonaws.com/
  testGet http://twitter.com/
  testGet https://mailchimp.com

  # See README.md as to why this is now disabled
  # testGet https://twitter.com/
}

runTests
