#!/bin/bash

# Changes:
#
#   ==========    ==========
#   TLA+          MY DIALECT
#   ==========    ==========
#   A /= B        A != B
#   A /\ B        A & B
#   A \/ B        A | B
#   A \union B    A ++ B
#   A \ B         A -- B
#   ==========    ==========

################################################################################

common='
  s/\t/  /g;
  s/ +$//;
'

to_tla='
  s, &(?= |$), /\\,g;
  s, \|(?= |$), \\/,g;
  s, != , /= ,g;
  s, \+\+(?= |$), \\union,g;
  s, --(?= |$), \\,g;
'

from_tla='
  s, /\\(?= |$), &,g;
  s, \\/(?= |$), \|,g;
  s, /= , != ,g;
  s, \\union(?= |$), ++,g;
  s, \\(?= |$), --,g;
'

################################################################################

reverse=0
if [ "$1" = "-r" ]; then
  reverse=1
  shift
fi

plan="$to_tla"
[ $reverse = 1 ] && plan="$from_tla"
plan="$common; $plan"

if [ $# -eq 0 ]; then
  exec perl -pe "$plan"
else
  exec perl -pi -e "$plan" "$@"
fi

