#!/bin/bash

dbdir="$(dirname "$0")"
backup="$dbdir"/backup-prod.sql

[ ! -r "$backup" ] && echo "File not found or readable: $backup" && exit 1

case "$1" in
  dev)  db=usecase_dev ;;
  test) db=usecase_test ;;
  prod) db=usecase_prod ; echo "WARNING: About to wipe PROD" ;;
  *) echo -e "Unknown db: '$1'.\nExpected [dev|test|prod]." >&2; exit 1
esac

cat "$backup" | "$dbdir"/sql-trns-dbname "$1" | sudo -u postgres -k psql
#cat "$dbdir"/backup-prod.sql | "$dbdir"/sql-trns-dbname "$1" | sudo -u postgres -k pg_restore -d $db --clean --create
#cat <&0

#[ -z "$1" ] && echo "USAGE: $(basename "$0") [dev|test|prod]" && exit 1
#conn="$dbdir/connect"
#[ ! -x "$conn" ] && echo "File not found: $conn" && exit 2
#cat "$dbdir"/backup-prod.sql | "$dbdir"/sql-trns-dbname "$1" | "$conn" "$1"
