#!/bin/bash

case "$1" in
  dev)  suffix=_dev ;;
  test) suffix=_test ;;
  prod) suffix=_prod ;;
  *) echo -e "Unknown db type: '$1'.\nExpected [dev|test|prod]." >&2; exit 1
esac

perl -pe "s/_(?:dev|test|prod)/$suffix/g"
