package shipreq.base.util

import cats.Semigroup
import japgolly.microlibs.stdlib_ext.StdlibExt._
import scala.collection.Iterable

object ScalaExt {

  type EndoFn[A] = A => A

  @inline final def none[A]: Option[A] = None

  implicit class BaseUtilExtAny[A](private val a: A) extends AnyVal {
    @inline def |>          [B]   (f: A => B)           : B      = f(a)
    @inline def <|                (f: A => Unit)        : A      = {f(a); a}
    @inline def mapStrengthL[B]   (f: A => B)           : (B, A) = (f(a), a)
    @inline def mapStrengthR[B]   (f: A => B)           : (A, B) = (a, f(a))
    @inline def tmap2       [B, C](b: A => B, c: A => C): (B, C) = (b(a), c(a))

    @inline def ifelse[B](c: A => Boolean, t: A => B, f: A => B): B =
      if (c(a)) t(a) else f(a)

    @inline def apif[B >: A](c: A => Boolean, t: A => B): B =
      if (c(a)) t(a) else a

    @inline def apif[B >: A](c: Boolean)(t: A => B): B =
      if (c) t(a) else a

    @inline def some: Option[A] = Some(a)
  }

  implicit class GenTravExt[T[x] <: Iterable[x], A](private val t: T[A]) extends AnyVal {
    def ifNonEmpty[B](f: T[A] => B): Option[B] =
      if (t.isEmpty) None else Some(f(t))
  }

  implicit class StringBuilderExt(val sb: StringBuilder) extends AnyVal {
    @inline def kv(k: String, v: Any): Unit = {
      sb append k
      sb append " = "
      sb append v
      ()
    }
    @inline def kv(k: String, v: Any, cond: Boolean): Unit = if (cond) kv(k, v)

    def mkStringF(start: String, sep: String, end: String)(fs: (StringBuilder => Any)*): Unit = {
      sb append start
      var nextSep = false
      for (f <- fs) {
        if (nextSep) sb append sep
        val b = sb.length
        f(sb)
        nextSep = sb.length != b
      }
      if (!nextSep) // undo sep if last function was NOP
        sb.setLength(sb.length - sep.length)
      sb append end
      ()
    }
  }

  implicit class StringExt(private val s: String) extends AnyVal {
    def flatMapSB(f: (Char, StringBuilder) => Unit): String =
      Util.quickSB(sb => s.foreach(c => f(c, sb)))
  }

  implicit class OptionExt[A](private val o: Option[A]) extends AnyVal {
    def ++(n: Option[A])(implicit s: Semigroup[A]): Option[A] =
      o.fold(n)(a =>
        n.fold(o)(b =>
          Some(s.combine(a, b))))
  }

  implicit class IteratorExtO2[A, B](private val as: Iterator[(A, Option[B])]) extends AnyVal {
    def filterDefined_2: Iterator[(A, B)] =
      as.filter(_._2.isDefined).map(_.map2(_.get))
  }

  implicit class LazyListOptionExt[A](private val s: LazyList[Option[A]]) extends AnyVal {
    def somes: LazyList[A] =
      s.filter(_.isDefined).map(_.get)
  }

  // Generated by bin/gen-function_ext

  @inline final implicit class Function1Ext[X,Y](private val x: X => Y) extends AnyVal {
    @inline def unify(y: X=>Y)(u: (=>Y,=>Y)=>Y): X=>Y = (a)=>u(x(a),y(a))
    @inline def composeA[A,B](y: (A,B)=>X): (A,B)=>Y = y andThenA x
    @inline def composeA[A,B,C](y: (A,B,C)=>X): (A,B,C)=>Y = y andThenA x
    @inline def composeA[A,B,C,D](y: (A,B,C,D)=>X): (A,B,C,D)=>Y = y andThenA x
    @inline def composeA[A,B,C,D,E](y: (A,B,C,D,E)=>X): (A,B,C,D,E)=>Y = y andThenA x
    @inline def composeA[A,B,C,D,E,F](y: (A,B,C,D,E,F)=>X): (A,B,C,D,E,F)=>Y = y andThenA x
    @inline def composeA[A,B,C,D,E,F,G](y: (A,B,C,D,E,F,G)=>X): (A,B,C,D,E,F,G)=>Y = y andThenA x
    @inline def composeA[A,B,C,D,E,F,G,H](y: (A,B,C,D,E,F,G,H)=>X): (A,B,C,D,E,F,G,H)=>Y = y andThenA x
    @inline def composeA[A,B,C,D,E,F,G,H,I](y: (A,B,C,D,E,F,G,H,I)=>X): (A,B,C,D,E,F,G,H,I)=>Y = y andThenA x
    def overTuple2: HomoTuple2Map[X,Y] = _ mapEach x
    def overTuple3: HomoTuple3Map[X,Y] = _ mapEach x
    def overTuple4: HomoTuple4Map[X,Y] = _ mapEach x
    def overTuple5: HomoTuple5Map[X,Y] = _ mapEach x
    def overTuple6: HomoTuple6Map[X,Y] = _ mapEach x
    def overTuple7: HomoTuple7Map[X,Y] = _ mapEach x
    def overTuple8: HomoTuple8Map[X,Y] = _ mapEach x
    def overTuple9: HomoTuple9Map[X,Y] = _ mapEach x
  }
  @inline final implicit class Function2Ext[A,B,R](private val x: (A,B) => R) extends AnyVal {
    @inline def andThenA[Z](y: R=>Z): (A,B)=>Z = (a,b)=>y(x(a,b))
    @inline def unify(y: (A,B)=>R)(u: (=>R,=>R)=>R): (A,B)=>R = (a,b)=>u(x(a,b),y(a,b))
  }
  @inline final implicit class Function3Ext[A,B,C,R](private val x: (A,B,C) => R) extends AnyVal {
    @inline def andThenA[Z](y: R=>Z): (A,B,C)=>Z = (a,b,c)=>y(x(a,b,c))
    @inline def unify(y: (A,B,C)=>R)(u: (=>R,=>R)=>R): (A,B,C)=>R = (a,b,c)=>u(x(a,b,c),y(a,b,c))
  }
  @inline final implicit class Function4Ext[A,B,C,D,R](private val x: (A,B,C,D) => R) extends AnyVal {
    @inline def andThenA[Z](y: R=>Z): (A,B,C,D)=>Z = (a,b,c,d)=>y(x(a,b,c,d))
    @inline def unify(y: (A,B,C,D)=>R)(u: (=>R,=>R)=>R): (A,B,C,D)=>R = (a,b,c,d)=>u(x(a,b,c,d),y(a,b,c,d))
  }
  @inline final implicit class Function5Ext[A,B,C,D,E,R](private val x: (A,B,C,D,E) => R) extends AnyVal {
    @inline def andThenA[Z](y: R=>Z): (A,B,C,D,E)=>Z = (a,b,c,d,e)=>y(x(a,b,c,d,e))
    @inline def unify(y: (A,B,C,D,E)=>R)(u: (=>R,=>R)=>R): (A,B,C,D,E)=>R = (a,b,c,d,e)=>u(x(a,b,c,d,e),y(a,b,c,d,e))
  }
  @inline final implicit class Function6Ext[A,B,C,D,E,F,R](private val x: (A,B,C,D,E,F) => R) extends AnyVal {
    @inline def andThenA[Z](y: R=>Z): (A,B,C,D,E,F)=>Z = (a,b,c,d,e,f)=>y(x(a,b,c,d,e,f))
    @inline def unify(y: (A,B,C,D,E,F)=>R)(u: (=>R,=>R)=>R): (A,B,C,D,E,F)=>R = (a,b,c,d,e,f)=>u(x(a,b,c,d,e,f),y(a,b,c,d,e,f))
  }
  @inline final implicit class Function7Ext[A,B,C,D,E,F,G,R](private val x: (A,B,C,D,E,F,G) => R) extends AnyVal {
    @inline def andThenA[Z](y: R=>Z): (A,B,C,D,E,F,G)=>Z = (a,b,c,d,e,f,g)=>y(x(a,b,c,d,e,f,g))
    @inline def unify(y: (A,B,C,D,E,F,G)=>R)(u: (=>R,=>R)=>R): (A,B,C,D,E,F,G)=>R = (a,b,c,d,e,f,g)=>u(x(a,b,c,d,e,f,g),y(a,b,c,d,e,f,g))
  }
  @inline final implicit class Function8Ext[A,B,C,D,E,F,G,H,R](private val x: (A,B,C,D,E,F,G,H) => R) extends AnyVal {
    @inline def andThenA[Z](y: R=>Z): (A,B,C,D,E,F,G,H)=>Z = (a,b,c,d,e,f,g,h)=>y(x(a,b,c,d,e,f,g,h))
    @inline def unify(y: (A,B,C,D,E,F,G,H)=>R)(u: (=>R,=>R)=>R): (A,B,C,D,E,F,G,H)=>R = (a,b,c,d,e,f,g,h)=>u(x(a,b,c,d,e,f,g,h),y(a,b,c,d,e,f,g,h))
  }
  @inline final implicit class Function9Ext[A,B,C,D,E,F,G,H,I,R](private val x: (A,B,C,D,E,F,G,H,I) => R) extends AnyVal {
    @inline def andThenA[Z](y: R=>Z): (A,B,C,D,E,F,G,H,I)=>Z = (a,b,c,d,e,f,g,h,i)=>y(x(a,b,c,d,e,f,g,h,i))
    @inline def unify(y: (A,B,C,D,E,F,G,H,I)=>R)(u: (=>R,=>R)=>R): (A,B,C,D,E,F,G,H,I)=>R = (a,b,c,d,e,f,g,h,i)=>u(x(a,b,c,d,e,f,g,h,i),y(a,b,c,d,e,f,g,h,i))
  }

  // Generated by bin/gen-tuple_ext-homo

  @inline final implicit class HomoTuple2Ext[A](private val t: (A, A)) extends AnyVal {
    @inline def mapEach[B](f: A => B): (B, B) = (f(t._1), f(t._2))
  }
  @inline final implicit class HomoTuple3Ext[A](private val t: (A, A, A)) extends AnyVal {
    @inline def mapEach[B](f: A => B): (B, B, B) = (f(t._1), f(t._2), f(t._3))
  }
  @inline final implicit class HomoTuple4Ext[A](private val t: (A, A, A, A)) extends AnyVal {
    @inline def mapEach[B](f: A => B): (B, B, B, B) = (f(t._1), f(t._2), f(t._3), f(t._4))
  }
  @inline final implicit class HomoTuple5Ext[A](private val t: (A, A, A, A, A)) extends AnyVal {
    @inline def mapEach[B](f: A => B): (B, B, B, B, B) = (f(t._1), f(t._2), f(t._3), f(t._4), f(t._5))
  }
  @inline final implicit class HomoTuple6Ext[A](private val t: (A, A, A, A, A, A)) extends AnyVal {
    @inline def mapEach[B](f: A => B): (B, B, B, B, B, B) = (f(t._1), f(t._2), f(t._3), f(t._4), f(t._5), f(t._6))
  }
  @inline final implicit class HomoTuple7Ext[A](private val t: (A, A, A, A, A, A, A)) extends AnyVal {
    @inline def mapEach[B](f: A => B): (B, B, B, B, B, B, B) = (f(t._1), f(t._2), f(t._3), f(t._4), f(t._5), f(t._6), f(t._7))
  }
  @inline final implicit class HomoTuple8Ext[A](private val t: (A, A, A, A, A, A, A, A)) extends AnyVal {
    @inline def mapEach[B](f: A => B): (B, B, B, B, B, B, B, B) = (f(t._1), f(t._2), f(t._3), f(t._4), f(t._5), f(t._6), f(t._7), f(t._8))
  }
  @inline final implicit class HomoTuple9Ext[A](private val t: (A, A, A, A, A, A, A, A, A)) extends AnyVal {
    @inline def mapEach[B](f: A => B): (B, B, B, B, B, B, B, B, B) = (f(t._1), f(t._2), f(t._3), f(t._4), f(t._5), f(t._6), f(t._7), f(t._8), f(t._9))
  }

  type HomoTuple2[A] = (A, A)
  type HomoTuple3[A] = (A, A, A)
  type HomoTuple4[A] = (A, A, A, A)
  type HomoTuple5[A] = (A, A, A, A, A)
  type HomoTuple6[A] = (A, A, A, A, A, A)
  type HomoTuple7[A] = (A, A, A, A, A, A, A)
  type HomoTuple8[A] = (A, A, A, A, A, A, A, A)
  type HomoTuple9[A] = (A, A, A, A, A, A, A, A, A)

  type HomoTuple2Map[A,B] = ((A, A)) => (B, B)
  type HomoTuple3Map[A,B] = ((A, A, A)) => (B, B, B)
  type HomoTuple4Map[A,B] = ((A, A, A, A)) => (B, B, B, B)
  type HomoTuple5Map[A,B] = ((A, A, A, A, A)) => (B, B, B, B, B)
  type HomoTuple6Map[A,B] = ((A, A, A, A, A, A)) => (B, B, B, B, B, B)
  type HomoTuple7Map[A,B] = ((A, A, A, A, A, A, A)) => (B, B, B, B, B, B, B)
  type HomoTuple8Map[A,B] = ((A, A, A, A, A, A, A, A)) => (B, B, B, B, B, B, B, B)
  type HomoTuple9Map[A,B] = ((A, A, A, A, A, A, A, A, A)) => (B, B, B, B, B, B, B, B, B)
}
