version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - cd DockerImages/shipreq-base
      - env|sort
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
      - docker pull $IMAGE_URL:latest || true
  build:
    commands:
      - ./build
  post_build:
    commands:
      - docker push $IMAGE_URL:git-$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push $IMAGE_URL:latest
