#!/bin/bash
cd "$(dirname "$0")" || exit 1

export PULL_REPO=930801536115.dkr.ecr.ap-southeast-2.amazonaws.com

export DEV_BUILD_ENV_URL="shipreq/dev/build_env"
export DEV_NODE_URL="shipreq/dev/node"
export DEV_POSTGRES_URL="shipreq/dev/postgres"
export NAT_URL="shipreq/nat"
export OPS_CADVISOR_URL="shipreq/ops/cadvisor"
export OPS_ECS_EXPORTER_URL="shipreq/ops/ecs_exporter"
export OPS_FILEBEAT_URL="shipreq/ops/filebeat"
export OPS_GRAFANA_URL="shipreq/ops/grafana"
export OPS_NODE_EXPORTER_URL="shipreq/ops/node_exporter"
export OPS_PORTAL_URL="shipreq/ops/portal"
export OPS_POSTGRES_EXPORTER_URL="shipreq/ops/postgres_exporter"
export OPS_PROMETHEUS_BIZ_URL="shipreq/ops/prometheus-biz"
export OPS_PROMETHEUS_TECH_URL="shipreq/ops/prometheus-tech"
export OPS_SQUID_EXPORTER_URL="shipreq/ops/squid_exporter"
export SHIPREQ_BASE_URL="shipreq/base"

exec ./build-all --no-push