#!/bin/bash

set -euo pipefail

# Parse args
pull=yes
push=yes
for arg in "$@"; do
  case "$arg" in
    --no-pull) pull=no ;;
    --no-push) push=no ;;
    *)
      echo "Usage: $0 [OPTION]..."
      echo
      echo "Options:"
      echo "  --no-pull    Don't pull Docker images"
      echo "  --no-push    Don't push Docker images/tags"
      exit 1
      ;;
  esac
done

# Prepare globals
cd "$(dirname "$0")"
images_root_dir="$(pwd)"
git_sha="$(git rev-parse --verify HEAD)"
echo "images_root_dir = $images_root_dir"
echo "git_sha         = $git_sha"
echo

function runcmd {
  echo "> $@"

  # Attempt to run in full
  fail=0
  "$@" || fail=$?

  # If we've failed, try again by removing the --cache-from args
  if [ $fail -ne 0 ]; then
    args=()
    skip_next=0
    changed=0
    for arg in "$@"; do
      if [ $skip_next -eq 1 ]; then
        skip_next=0
      elif [ "$arg" = --cache-from ]; then
        skip_next=1
        changed=1
      else
        args+=("$arg")
      fi
    done
    if [ $changed -eq 0 ]; then
      return $fail
    else
      echo "Trying again without --cache-from ..."
      echo "> ${args[@]}"
      "${args[@]}"
    fi
  fi
}

function build_and_deploy {
  image_dir="$1"
  image_url="$2"

  echo "================================================================================"
  echo "$image_dir"
  echo "================================================================================"

  cd "${images_root_dir}/${image_dir}"

  src_md5=$(find . -type f -exec md5sum {} \; | LC_COLLATE=C sort | md5sum | sed 's/ .*//')
  echo "src_md5      = $src_md5"

  image_by_md5="${image_url}:src-${src_md5}"
  image_by_git="${image_url}:git-${git_sha}"
  image_latest="${image_url}:latest"
  echo "image_by_md5 = $image_by_md5"
  echo "image_by_git = $image_by_git"
  echo "image_latest = $image_latest"

  pull_repo_prefix=
  [ -n "${PULL_REPO:-}" ] && pull_repo_prefix="${PULL_REPO}/"

  if [ $pull = yes ]; then
    echo "Pulling..."
    runcmd docker pull "${pull_repo_prefix}${image_by_md5}" \
      || runcmd docker pull "${pull_repo_prefix}${image_latest}" \
      || true
  fi

  image_exists=yes
  x="$(docker inspect "${pull_repo_prefix}${image_by_md5}" || true)"
  [ "$x" = '[]' ] && image_exists=no
  echo "image_exists = $image_exists"

  if [ $image_exists = no ]; then
    echo "Building..."
    runcmd docker build \
      --cache-from "${image_by_md5}" \
      --cache-from "${image_latest}" \
      --cache-from "${pull_repo_prefix}${image_by_md5}" \
      --cache-from "${pull_repo_prefix}${image_latest}" \
      -t "${image_by_md5}" \
      -t "${image_by_git}" \
      -t "${image_latest}" \
      .
  else
    echo "No need to build. Retagging..."
    runcmd docker tag "${pull_repo_prefix}${image_by_md5}" "${image_by_git}"
    runcmd docker tag "${pull_repo_prefix}${image_by_md5}" "${image_latest}"
  fi

  if [ $push = yes ]; then
    echo "Pushing..."
    [ $image_exists = no ] && runcmd docker push "${image_by_md5}"
    runcmd docker push "${image_by_git}"
    runcmd docker push "${image_latest}"
  fi

  echo "Done"
  echo
}

build_and_deploy  analytics_proxy        "${ANALYTICS_PROXY_URL}"
build_and_deploy  dev-node               "${DEV_NODE_URL}"
build_and_deploy  dev-postgres           "${DEV_POSTGRES_URL}"
build_and_deploy  nat                    "${NAT_URL}"
build_and_deploy  ops-cadvisor           "${OPS_CADVISOR_URL}"
build_and_deploy  ops-ecs_exporter       "${OPS_ECS_EXPORTER_URL}"
build_and_deploy  ops-filebeat           "${OPS_FILEBEAT_URL}"
build_and_deploy  ops-grafana            "${OPS_GRAFANA_URL}"
build_and_deploy  ops-node_exporter      "${OPS_NODE_EXPORTER_URL}"
build_and_deploy  ops-portal             "${OPS_PORTAL_URL}"
build_and_deploy  ops-postgres_exporter  "${OPS_POSTGRES_EXPORTER_URL}"
build_and_deploy  ops-prometheus-biz     "${OPS_PROMETHEUS_BIZ_URL}"
build_and_deploy  ops-prometheus-tech    "${OPS_PROMETHEUS_TECH_URL}"
build_and_deploy  ops-squid_exporter     "${OPS_SQUID_EXPORTER_URL}"
build_and_deploy  shipreq-base           "${SHIPREQ_BASE_URL}"
build_and_deploy  dev-build_env          "${DEV_BUILD_ENV_URL}" # Last because it's huge and not needed locally
