package shipreq.base.util

object ScalaExt {

  @inline final def none[A]: Option[A] = None

  implicit class BaseUtilExtAny[A](val a: A) extends AnyVal {
    @inline def |>[B](f: A => B): B = f(a)
    @inline def |&>[B](f: A => B): (A, B) = (a, f(a))
    @inline def tmap2[B, C](b: A => B, c: A => C): (B, C) = (b(a), c(a))
    @inline def some: Option[A] = Some(a)
  }

  implicit class StringBuilderExt(val sb: StringBuilder) extends AnyVal {
    @inline def kv(k: String, v: Any): Unit = {
      sb append k
      sb append " = "
      sb append v
    }
    @inline def kv(k: String, v: Any, cond: Boolean): Unit = if (cond) kv(k, v)

    def mkStringF(start: String, sep: String, end: String)(fs: (StringBuilder => Any)*): Unit = {
      sb append start
      var nextSep = false
      for (f <- fs) {
        if (nextSep) sb append sep
        val b = sb.length
        f(sb)
        nextSep = sb.length != b
      }
      if (!nextSep) // undo sep if last function was NOP
        sb.setLength(sb.length - sep.length)
      sb append end
    }
  }

  implicit class StringExt(val s: String) extends AnyVal {
    def flatMapSB(f: (Char, StringBuilder) => Unit): String =
      Util.quickSB(sb => s.foreach(c => f(c, sb)))
  }

  // Generated by bin/gen-function_ext

  implicit class Function2Ext[A,B,R](val x: (A,B) ⇒ R) extends AnyVal {
    def andThenA[Z](y: R⇒Z): (A,B)⇒Z = (a,b)⇒y(x(a,b))
  }
  implicit class Function3Ext[A,B,C,R](val x: (A,B,C) ⇒ R) extends AnyVal {
    def andThenA[Z](y: R⇒Z): (A,B,C)⇒Z = (a,b,c)⇒y(x(a,b,c))
  }
  implicit class Function4Ext[A,B,C,D,R](val x: (A,B,C,D) ⇒ R) extends AnyVal {
    def andThenA[Z](y: R⇒Z): (A,B,C,D)⇒Z = (a,b,c,d)⇒y(x(a,b,c,d))
  }
  implicit class Function5Ext[A,B,C,D,E,R](val x: (A,B,C,D,E) ⇒ R) extends AnyVal {
    def andThenA[Z](y: R⇒Z): (A,B,C,D,E)⇒Z = (a,b,c,d,e)⇒y(x(a,b,c,d,e))
  }
  implicit class Function6Ext[A,B,C,D,E,F,R](val x: (A,B,C,D,E,F) ⇒ R) extends AnyVal {
    def andThenA[Z](y: R⇒Z): (A,B,C,D,E,F)⇒Z = (a,b,c,d,e,f)⇒y(x(a,b,c,d,e,f))
  }
  implicit class Function7Ext[A,B,C,D,E,F,G,R](val x: (A,B,C,D,E,F,G) ⇒ R) extends AnyVal {
    def andThenA[Z](y: R⇒Z): (A,B,C,D,E,F,G)⇒Z = (a,b,c,d,e,f,g)⇒y(x(a,b,c,d,e,f,g))
  }
  implicit class Function8Ext[A,B,C,D,E,F,G,H,R](val x: (A,B,C,D,E,F,G,H) ⇒ R) extends AnyVal {
    def andThenA[Z](y: R⇒Z): (A,B,C,D,E,F,G,H)⇒Z = (a,b,c,d,e,f,g,h)⇒y(x(a,b,c,d,e,f,g,h))
  }
  implicit class Function9Ext[A,B,C,D,E,F,G,H,I,R](val x: (A,B,C,D,E,F,G,H,I) ⇒ R) extends AnyVal {
    def andThenA[Z](y: R⇒Z): (A,B,C,D,E,F,G,H,I)⇒Z = (a,b,c,d,e,f,g,h,i)⇒y(x(a,b,c,d,e,f,g,h,i))
  }
  implicit class Function1Ext[X,Y](val x: X ⇒ Y) extends AnyVal {
    def composeA[A,B](y: (A,B)⇒X): (A,B)⇒Y = y andThenA x
    def composeA[A,B,C](y: (A,B,C)⇒X): (A,B,C)⇒Y = y andThenA x
    def composeA[A,B,C,D](y: (A,B,C,D)⇒X): (A,B,C,D)⇒Y = y andThenA x
    def composeA[A,B,C,D,E](y: (A,B,C,D,E)⇒X): (A,B,C,D,E)⇒Y = y andThenA x
    def composeA[A,B,C,D,E,F](y: (A,B,C,D,E,F)⇒X): (A,B,C,D,E,F)⇒Y = y andThenA x
    def composeA[A,B,C,D,E,F,G](y: (A,B,C,D,E,F,G)⇒X): (A,B,C,D,E,F,G)⇒Y = y andThenA x
    def composeA[A,B,C,D,E,F,G,H](y: (A,B,C,D,E,F,G,H)⇒X): (A,B,C,D,E,F,G,H)⇒Y = y andThenA x
    def composeA[A,B,C,D,E,F,G,H,I](y: (A,B,C,D,E,F,G,H,I)⇒X): (A,B,C,D,E,F,G,H,I)⇒Y = y andThenA x
  }

  // Generated by bin/gen-tuple_ext

  implicit class Tuple2Ext[A, B](val t: (A, B)) extends AnyVal {
    def map1[X](f: A => X): (X, B) = (f(t._1), t._2)
    def map2[X](f: B => X): (A, X) = (t._1, f(t._2))
    def put1[X](x: X): (X, B) = (x, t._2)
    def put2[X](x: X): (A, X) = (t._1, x)
  }
  implicit class Tuple3Ext[A, B, C](val t: (A, B, C)) extends AnyVal {
    def map1[X](f: A => X): (X, B, C) = (f(t._1), t._2, t._3)
    def map2[X](f: B => X): (A, X, C) = (t._1, f(t._2), t._3)
    def map3[X](f: C => X): (A, B, X) = (t._1, t._2, f(t._3))
    def put1[X](x: X): (X, B, C) = (x, t._2, t._3)
    def put2[X](x: X): (A, X, C) = (t._1, x, t._3)
    def put3[X](x: X): (A, B, X) = (t._1, t._2, x)
  }
  implicit class Tuple4Ext[A, B, C, D](val t: (A, B, C, D)) extends AnyVal {
    def map1[X](f: A => X): (X, B, C, D) = (f(t._1), t._2, t._3, t._4)
    def map2[X](f: B => X): (A, X, C, D) = (t._1, f(t._2), t._3, t._4)
    def map3[X](f: C => X): (A, B, X, D) = (t._1, t._2, f(t._3), t._4)
    def map4[X](f: D => X): (A, B, C, X) = (t._1, t._2, t._3, f(t._4))
    def put1[X](x: X): (X, B, C, D) = (x, t._2, t._3, t._4)
    def put2[X](x: X): (A, X, C, D) = (t._1, x, t._3, t._4)
    def put3[X](x: X): (A, B, X, D) = (t._1, t._2, x, t._4)
    def put4[X](x: X): (A, B, C, X) = (t._1, t._2, t._3, x)
  }
  implicit class Tuple5Ext[A, B, C, D, E](val t: (A, B, C, D, E)) extends AnyVal {
    def map1[X](f: A => X): (X, B, C, D, E) = (f(t._1), t._2, t._3, t._4, t._5)
    def map2[X](f: B => X): (A, X, C, D, E) = (t._1, f(t._2), t._3, t._4, t._5)
    def map3[X](f: C => X): (A, B, X, D, E) = (t._1, t._2, f(t._3), t._4, t._5)
    def map4[X](f: D => X): (A, B, C, X, E) = (t._1, t._2, t._3, f(t._4), t._5)
    def map5[X](f: E => X): (A, B, C, D, X) = (t._1, t._2, t._3, t._4, f(t._5))
    def put1[X](x: X): (X, B, C, D, E) = (x, t._2, t._3, t._4, t._5)
    def put2[X](x: X): (A, X, C, D, E) = (t._1, x, t._3, t._4, t._5)
    def put3[X](x: X): (A, B, X, D, E) = (t._1, t._2, x, t._4, t._5)
    def put4[X](x: X): (A, B, C, X, E) = (t._1, t._2, t._3, x, t._5)
    def put5[X](x: X): (A, B, C, D, X) = (t._1, t._2, t._3, t._4, x)
  }
  implicit class Tuple6Ext[A, B, C, D, E, F](val t: (A, B, C, D, E, F)) extends AnyVal {
    def map1[X](f: A => X): (X, B, C, D, E, F) = (f(t._1), t._2, t._3, t._4, t._5, t._6)
    def map2[X](f: B => X): (A, X, C, D, E, F) = (t._1, f(t._2), t._3, t._4, t._5, t._6)
    def map3[X](f: C => X): (A, B, X, D, E, F) = (t._1, t._2, f(t._3), t._4, t._5, t._6)
    def map4[X](f: D => X): (A, B, C, X, E, F) = (t._1, t._2, t._3, f(t._4), t._5, t._6)
    def map5[X](f: E => X): (A, B, C, D, X, F) = (t._1, t._2, t._3, t._4, f(t._5), t._6)
    def map6[X](f: F => X): (A, B, C, D, E, X) = (t._1, t._2, t._3, t._4, t._5, f(t._6))
    def put1[X](x: X): (X, B, C, D, E, F) = (x, t._2, t._3, t._4, t._5, t._6)
    def put2[X](x: X): (A, X, C, D, E, F) = (t._1, x, t._3, t._4, t._5, t._6)
    def put3[X](x: X): (A, B, X, D, E, F) = (t._1, t._2, x, t._4, t._5, t._6)
    def put4[X](x: X): (A, B, C, X, E, F) = (t._1, t._2, t._3, x, t._5, t._6)
    def put5[X](x: X): (A, B, C, D, X, F) = (t._1, t._2, t._3, t._4, x, t._6)
    def put6[X](x: X): (A, B, C, D, E, X) = (t._1, t._2, t._3, t._4, t._5, x)
  }
  implicit class Tuple7Ext[A, B, C, D, E, F, G](val t: (A, B, C, D, E, F, G)) extends AnyVal {
    def map1[X](f: A => X): (X, B, C, D, E, F, G) = (f(t._1), t._2, t._3, t._4, t._5, t._6, t._7)
    def map2[X](f: B => X): (A, X, C, D, E, F, G) = (t._1, f(t._2), t._3, t._4, t._5, t._6, t._7)
    def map3[X](f: C => X): (A, B, X, D, E, F, G) = (t._1, t._2, f(t._3), t._4, t._5, t._6, t._7)
    def map4[X](f: D => X): (A, B, C, X, E, F, G) = (t._1, t._2, t._3, f(t._4), t._5, t._6, t._7)
    def map5[X](f: E => X): (A, B, C, D, X, F, G) = (t._1, t._2, t._3, t._4, f(t._5), t._6, t._7)
    def map6[X](f: F => X): (A, B, C, D, E, X, G) = (t._1, t._2, t._3, t._4, t._5, f(t._6), t._7)
    def map7[X](f: G => X): (A, B, C, D, E, F, X) = (t._1, t._2, t._3, t._4, t._5, t._6, f(t._7))
    def put1[X](x: X): (X, B, C, D, E, F, G) = (x, t._2, t._3, t._4, t._5, t._6, t._7)
    def put2[X](x: X): (A, X, C, D, E, F, G) = (t._1, x, t._3, t._4, t._5, t._6, t._7)
    def put3[X](x: X): (A, B, X, D, E, F, G) = (t._1, t._2, x, t._4, t._5, t._6, t._7)
    def put4[X](x: X): (A, B, C, X, E, F, G) = (t._1, t._2, t._3, x, t._5, t._6, t._7)
    def put5[X](x: X): (A, B, C, D, X, F, G) = (t._1, t._2, t._3, t._4, x, t._6, t._7)
    def put6[X](x: X): (A, B, C, D, E, X, G) = (t._1, t._2, t._3, t._4, t._5, x, t._7)
    def put7[X](x: X): (A, B, C, D, E, F, X) = (t._1, t._2, t._3, t._4, t._5, t._6, x)
  }
  implicit class Tuple8Ext[A, B, C, D, E, F, G, H](val t: (A, B, C, D, E, F, G, H)) extends AnyVal {
    def map1[X](f: A => X): (X, B, C, D, E, F, G, H) = (f(t._1), t._2, t._3, t._4, t._5, t._6, t._7, t._8)
    def map2[X](f: B => X): (A, X, C, D, E, F, G, H) = (t._1, f(t._2), t._3, t._4, t._5, t._6, t._7, t._8)
    def map3[X](f: C => X): (A, B, X, D, E, F, G, H) = (t._1, t._2, f(t._3), t._4, t._5, t._6, t._7, t._8)
    def map4[X](f: D => X): (A, B, C, X, E, F, G, H) = (t._1, t._2, t._3, f(t._4), t._5, t._6, t._7, t._8)
    def map5[X](f: E => X): (A, B, C, D, X, F, G, H) = (t._1, t._2, t._3, t._4, f(t._5), t._6, t._7, t._8)
    def map6[X](f: F => X): (A, B, C, D, E, X, G, H) = (t._1, t._2, t._3, t._4, t._5, f(t._6), t._7, t._8)
    def map7[X](f: G => X): (A, B, C, D, E, F, X, H) = (t._1, t._2, t._3, t._4, t._5, t._6, f(t._7), t._8)
    def map8[X](f: H => X): (A, B, C, D, E, F, G, X) = (t._1, t._2, t._3, t._4, t._5, t._6, t._7, f(t._8))
    def put1[X](x: X): (X, B, C, D, E, F, G, H) = (x, t._2, t._3, t._4, t._5, t._6, t._7, t._8)
    def put2[X](x: X): (A, X, C, D, E, F, G, H) = (t._1, x, t._3, t._4, t._5, t._6, t._7, t._8)
    def put3[X](x: X): (A, B, X, D, E, F, G, H) = (t._1, t._2, x, t._4, t._5, t._6, t._7, t._8)
    def put4[X](x: X): (A, B, C, X, E, F, G, H) = (t._1, t._2, t._3, x, t._5, t._6, t._7, t._8)
    def put5[X](x: X): (A, B, C, D, X, F, G, H) = (t._1, t._2, t._3, t._4, x, t._6, t._7, t._8)
    def put6[X](x: X): (A, B, C, D, E, X, G, H) = (t._1, t._2, t._3, t._4, t._5, x, t._7, t._8)
    def put7[X](x: X): (A, B, C, D, E, F, X, H) = (t._1, t._2, t._3, t._4, t._5, t._6, x, t._8)
    def put8[X](x: X): (A, B, C, D, E, F, G, X) = (t._1, t._2, t._3, t._4, t._5, t._6, t._7, x)
  }
  implicit class Tuple9Ext[A, B, C, D, E, F, G, H, I](val t: (A, B, C, D, E, F, G, H, I)) extends AnyVal {
    def map1[X](f: A => X): (X, B, C, D, E, F, G, H, I) = (f(t._1), t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9)
    def map2[X](f: B => X): (A, X, C, D, E, F, G, H, I) = (t._1, f(t._2), t._3, t._4, t._5, t._6, t._7, t._8, t._9)
    def map3[X](f: C => X): (A, B, X, D, E, F, G, H, I) = (t._1, t._2, f(t._3), t._4, t._5, t._6, t._7, t._8, t._9)
    def map4[X](f: D => X): (A, B, C, X, E, F, G, H, I) = (t._1, t._2, t._3, f(t._4), t._5, t._6, t._7, t._8, t._9)
    def map5[X](f: E => X): (A, B, C, D, X, F, G, H, I) = (t._1, t._2, t._3, t._4, f(t._5), t._6, t._7, t._8, t._9)
    def map6[X](f: F => X): (A, B, C, D, E, X, G, H, I) = (t._1, t._2, t._3, t._4, t._5, f(t._6), t._7, t._8, t._9)
    def map7[X](f: G => X): (A, B, C, D, E, F, X, H, I) = (t._1, t._2, t._3, t._4, t._5, t._6, f(t._7), t._8, t._9)
    def map8[X](f: H => X): (A, B, C, D, E, F, G, X, I) = (t._1, t._2, t._3, t._4, t._5, t._6, t._7, f(t._8), t._9)
    def map9[X](f: I => X): (A, B, C, D, E, F, G, H, X) = (t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, f(t._9))
    def put1[X](x: X): (X, B, C, D, E, F, G, H, I) = (x, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9)
    def put2[X](x: X): (A, X, C, D, E, F, G, H, I) = (t._1, x, t._3, t._4, t._5, t._6, t._7, t._8, t._9)
    def put3[X](x: X): (A, B, X, D, E, F, G, H, I) = (t._1, t._2, x, t._4, t._5, t._6, t._7, t._8, t._9)
    def put4[X](x: X): (A, B, C, X, E, F, G, H, I) = (t._1, t._2, t._3, x, t._5, t._6, t._7, t._8, t._9)
    def put5[X](x: X): (A, B, C, D, X, F, G, H, I) = (t._1, t._2, t._3, t._4, x, t._6, t._7, t._8, t._9)
    def put6[X](x: X): (A, B, C, D, E, X, G, H, I) = (t._1, t._2, t._3, t._4, t._5, x, t._7, t._8, t._9)
    def put7[X](x: X): (A, B, C, D, E, F, X, H, I) = (t._1, t._2, t._3, t._4, t._5, t._6, x, t._8, t._9)
    def put8[X](x: X): (A, B, C, D, E, F, G, X, I) = (t._1, t._2, t._3, t._4, t._5, t._6, t._7, x, t._9)
    def put9[X](x: X): (A, B, C, D, E, F, G, H, X) = (t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, x)
  }
}
