imports:
- path: db.jinja
- path: cluster.jinja

resources:
- name: cluster
  type: cluster.jinja
  properties:
    zone: australia-southeast1-c
- name: db
  type: db.jinja
  properties:
    zone: australia-southeast1-c
