#!/bin/bash

myip="$(dirname "$0")/../util/ip-mine"
[ ! -e "$myip" ] && echo "File not found: $myip" && exit 1

if [ $# -ne 2 ]; then
  echo "Usage: $0 <group name> (<ip> | myip)"
  exit 1
fi

name="$1"
ip="$2"
[ "$ip" == myip ] && ip=$($myip)

echo "=== Adding ($ip)"
for port in 22 5432; do
  ec2-authorize "$name" -P tcp -p $port --cidr "$ip"/32
done
echo

echo "=== Confirmation"
ec2-describe-group "$1"


