#!/bin/bash
cd $(dirname "$0") || exit 1

[ -z "$1" ] && echo "Usage: $0 <public DNS>" && exit 1

jetty_alias=jetty
jetty_inst=$(readlink "$jetty_alias")
[ ! -e "$jetty_inst" ] && echo "Jetty not found: $jetty_inst" && exit 2

rsync -vzrRlptSihOJ --skip-compress=jar \
  --exclude={jetty.pid,jetty.state,demo-base,log,work,'*.war','.*.sw?',production.golly.props,'*localhost*'} \
  "$jetty_inst" "$jetty_alias" $(<deployment-user)@"$1":

