#!/bin/bash

cd "$(dirname "$0")"

d=/tmp/shipreq.sbt/webapp-server/target/scala-2.11
[ ! -e $d ] && echo "Directory not found: $d" && exit 1
s="$(ls -1rt $d | fgrep .war | tail -1)"
[ -z "$s" ] && echo "No WARs found in $d" && exit 1
echo "Found: $d/$s"

echo "Installing..."
cp -p $d/$s webapp/webapps/shipreq.war \
  && echo && ./war-compress_static_resources \
  && echo && ./war-force_https \
  && echo && echo "--------------------------------------------------------------------------------" \
  && ./war-inspect
