#!/bin/bash
cd $(dirname "$0") || exit 1

[ $# -ne 1 ] && echo "Usage: $0 <jetty.tar.gz>" && exit 1

j="$1"
dirhead=$(tar tvzf "$j" | cut -b40- | perl -pe 's!^.*?\s(\S+?)/.*$!\1!' | sort -u)
[ $(echo "$dirhead" | wc -l) -ne 1 ] && echo -e "Expected one line:\n$dirhead" && exit 2
v=$(echo "$dirhead" | perl -pe 's/^(?:.+-([91]\d*\.\d+\.\d+).v20\d{6}.*)|.*$/\1/')
[ -z "$v" ] && echo "Unable to parse version: $dirhead" && exit 3
tgt=jetty-$v
[ -e "$dirhead" ] && echo "Dir already exists: $dirhead" && exit 4
[ -e "$tgt" ] && echo "Dir already exists: $tgt" && exit 5
ja=jetty

[ -e $ja ] && git rm -r $(readlink $ja)
echo "Installing into $tgt..."
tar xzf "$j" \
  && mv "$dirhead" $tgt \
  && rm -f $ja \
  && ln -s $tgt $ja \
  && git add $tgt $ja \
  && du -sh $tgt \
  && echo && echo "git commit -m 'Upgrade Jetty to $v [1/2]'" && echo
