#!/bin/bash

function encrypt {
  echo ">>> $1"
  gpg --cipher-algo AES256 --symmetric -o "$1.gpg" "$1"
  echo
}

encrypt resources/production.shipreq.props
encrypt start.d/ssl-passwords.ini

#gpgconf --reload gpg-agent
