#!/bin/bash

basedir="$(cd "$(dirname "$0")"/webapp && pwd)"
wardir="$basedir/webapps"
war="$wardir/shipreq.war"
webxml=WEB-INF/web.xml

echo "Forcing HTTPS in:"
echo "  $war"
[ ! -e "$war" ] && echo "File not found"  && exit 1

tmp=/tmp/$(date +%Y%m%d-%H%M%S)-$$
mkdir $tmp
cd $tmp || exit 1

unzip -q "$war" $webxml \
  && perl -pi -e 's!(?<=<transport-guarantee>)\s*NONE\s*(?=<)!CONFIDENTIAL!' $webxml \
  && zip -9 "$war" $webxml

cd /
rm -rf $tmp
