#!/bin/bash

f="$(dirname "$0")/webapps/shipreq.war"
#echo "WAR: $f"
[ ! -e "$f" ] && echo "File not found: $f" && exit 1

stat -L -c 'Size: %s bytes.' "$f"

echo "Properties:"
unzip -p "$f" WEB-INF/classes/build.properties | sort | sed 's/^/  /'

echo "Compression:"
gzout=$(unzip -l "$f" '*.gz')
gztail=$(echo "$gzout" | tail -1)
uncomp=$(echo "$gzout" | fgrep .gz | perl -pe 's/(\s+\S+){3}\s+//; s/\.gz$//' | xargs unzip -l "$f" | tail -1)
echo "$uncomp" | awk '{print "  Before: " $2 " files @ " $1 " bytes." }'
echo "$gztail" | awk '{print "  After : " $2 " files @ " $1 " bytes." }'
echo "$gztail $uncomp" | awk '{print "  Delta : " ($1/$4*100) "%"}'
