#!/bin/bash

wardir="$(cd "$(dirname "$0")/webapps" && pwd)"
war="$wardir/shipreq.war"
echo "Compressing static resources in:"
echo "  $war"
[ ! -e "$war" ] && echo "File not found"  && exit 1

tmp=/tmp/$(date +%Y%m%d-%H%M%S)-$$
mkdir $tmp
cd $tmp || exit 1

echo "Extracting..."
unzip -q "$war" {css,js}/'*' 'img/*.svg'
find -name '*.gz' -exec rm {} +

echo "Compressing..."
find -type f -exec gzip -9 {} +

echo "Bundling..."
find -name '*.gz' -exec zip -0q "$war" {} +

cd /
rm -rf $tmp
