#!/bin/bash

cd $(dirname "$0") || exit 1

basedir=$(pwd)
wardir="$basedir/webapp/webapps"
war="$wardir/shipreq.war"
patch="$basedir/gzip.patch"
webxml=WEB-INF/web.xml

echo "Enabling GZIP in:"
echo "  $war"
[ ! -e "$war" ] && echo "File not found"  && exit 1

tmp=/tmp/$(date +%Y%m%d-%H%M%S)-$$
mkdir $tmp
cd $tmp || exit 1

unzip -q "$war" $webxml \
 && patch -p6 -i "$patch" \
 && zip -9 "$war" $webxml

cd /
rm -rf $tmp
