#!/bin/bash

#compress="gzip -9"
compress="pigz -11 -b 96"

wardir="$(cd "$(dirname "$0")/webapp/webapps" && pwd)"
war="$wardir/shipreq.war"
echo "Compressing static resources in:"
echo "  $war"
[ ! -e "$war" ] && echo "File not found"  && exit 1

tmp=/tmp/$(date +%Y%m%d-%H%M%S)-$$
mkdir $tmp
cd $tmp || exit 1

echo "Extracting..."
unzip -q "$war" 'assets/*'
find \( -name '*.gz' -o -name '*.woff' \) -exec rm {} +

echo "Compressing..."
#find -type f -exec $compress {} +
find -type f | parallel --no-notice $compress

echo "Bundling..."
find -name '*.gz' -exec zip -0q "$war" {} +

cd /
rm -rf $tmp
