#!/bin/bash

cd $(dirname "$0") || exit 1

JETTY_HOME=$(cd ../jetty && pwd)
[ ! -e "$JETTY_HOME" ] && echo "JETTY_HOME not found: $JETTY_HOME" && exit 1
JETTY_BASE=$(pwd)

JETTY_HOME="$JETTY_HOME" \
JETTY_BASE="$JETTY_BASE" \
JETTY_LOGS="$JETTY_BASE/log" \
$(./authbind) "$JETTY_HOME/bin/jetty.sh" "$@"
