#!/bin/bash

cd $(dirname "$0") || exit 1

./jetty stop

[ -n "$(jps -l | fgrep jetty)" ] && echo "Jetty still running." && exit 1

time ./jetty start
echo
echo
exec tail -50f "log/$(ls -1rt log | grep '^jetty' | tail -1)"
