#!/bin/bash

cd $(dirname "$0") || exit 1

function decrypt {
  raw="$1"
  enc="$raw.gpg"
  echo "$raw <<< $enc"
  gpg -o "$raw" -d "$enc" && chmod 600 "$raw"
  echo
}

decrypt resources/production.shipreq.props
decrypt start.d/ssl-passwords.ini

