#!/bin/bash

cd $(dirname "$0") || exit 1

function encrypt {
  raw="$1"
  enc="$raw.gpg"
  echo "$raw >>> $enc"
  gpg --cipher-algo AES256 --symmetric -o "$enc" "$raw"
  echo
}

encrypt resources/production.shipreq.props
encrypt start.d/ssl-passwords.ini

#gpgconf --reload gpg-agent
