
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE FUNCTION archive_usrd_name() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  insert into usrh_name(usr_id, name) values(OLD.usr_id, OLD.name);
  return NEW;
END;
$$;

CREATE FUNCTION to_iso8601_str(timestamp with time zone) RETURNS character varying
    LANGUAGE sql IMMUTABLE
    AS $_$
  select to_char($1 at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
$_$;

CREATE FUNCTION usr_login_stats_update() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN

    update usr
    set login_count   = login_count + 1
       ,last_login_at = NEW.time
       ,last_login_ip = NEW.ip -------------- changed to accept NULL here
    where id = NEW.usr_id;

    RETURN NULL;
END;
$$;

SET default_with_oids = false;

CREATE TABLE event (
    project_id bigint NOT NULL,
    ord integer NOT NULL,
    type_id smallint NOT NULL,
    data_id integer,
    data_id_type "char" NOT NULL,
    data json,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT event_ord_check CHECK ((ord > 0)),
    CONSTRAINT event_type_id_check CHECK ((type_id >= 0))
);

COMMENT ON TABLE event IS 'An append-only sequence of modification events applied to an empty project.';

COMMENT ON COLUMN event.ord IS 'Order in which events for a Project are to be applied.';

COMMENT ON COLUMN event.type_id IS 'A number representing the type of event. Defined and maintained in Scala only.';

COMMENT ON COLUMN event.data_id IS 'Meaning depends on event type. Usually the local ID of an object in the Project.';

COMMENT ON COLUMN event.data_id_type IS 'The type of data_id as IDs can be polymorphic.';

COMMENT ON COLUMN event.data IS 'Meaning and format depends on event type.';

CREATE SEQUENCE project_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE project (
    id bigint DEFAULT nextval('project_seq'::regclass) NOT NULL,
    usr_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    init_events smallint NOT NULL,
    CONSTRAINT project_init_events_check CHECK ((init_events >= 0))
);

COMMENT ON COLUMN project.init_events IS 'The number of synthetic events generated by ShipReq (not the user directly) when the project was created.';

CREATE SEQUENCE usr_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE usr (
    id bigint DEFAULT nextval('usr_seq'::regclass) NOT NULL,
    username character varying,
    email character varying NOT NULL,
    password character varying,
    password_salt character varying,
    password_changed_at timestamp with time zone,
    confirmation_token character varying,
    confirmation_sent_at timestamp with time zone NOT NULL,
    confirmed_at timestamp with time zone,
    reset_password_token character varying,
    reset_password_sent_at timestamp with time zone,
    reset_password_req_count integer DEFAULT 0 NOT NULL,
    login_count integer DEFAULT 0 NOT NULL,
    last_login_at timestamp with time zone,
    last_login_ip character varying,
    roles character varying,
    CONSTRAINT usr_confirmation_invariants CHECK (
CASE
    WHEN (confirmed_at IS NULL) THEN ((username IS NULL) AND (password IS NULL) AND (password_salt IS NULL) AND (password_changed_at IS NULL) AND (confirmation_token IS NOT NULL) AND (reset_password_req_count = 0) AND (login_count = 0))
    ELSE ((username IS NOT NULL) AND (password IS NOT NULL) AND (password_salt IS NOT NULL) AND (password_changed_at IS NOT NULL) AND (confirmation_token IS NULL) AND (confirmed_at >= confirmation_sent_at) AND (reset_password_req_count >= 0) AND (login_count >= 0))
END),
    CONSTRAINT usr_login_meta CHECK (
CASE
    WHEN (login_count = 0) THEN ((last_login_at IS NULL) AND (last_login_ip IS NULL))
    ELSE (last_login_at IS NOT NULL)
END),
    CONSTRAINT usr_reset_password_meta CHECK (
CASE
    WHEN (reset_password_req_count = 0) THEN ((reset_password_token IS NULL) AND (reset_password_sent_at IS NULL))
    ELSE (reset_password_sent_at IS NOT NULL)
END),
    CONSTRAINT usr_roles_check CHECK (((roles IS NULL) OR ((roles)::text ~ '^[a-z]+(,[a-z]+)*$'::text)))
);

CREATE TABLE usrd (
    usr_id bigint NOT NULL,
    name character varying NOT NULL,
    newsletter boolean NOT NULL
);

CREATE VIEW taskman_users_v01 AS
 SELECT usr.id,
    usr.username,
    usr.email,
    usrd.name,
    usrd.newsletter,
    usr.confirmed_at AS joined
   FROM (usr
     LEFT JOIN usrd ON ((usr.id = usrd.usr_id)))
  WHERE (usr.username IS NOT NULL);

CREATE TABLE usr_login_log (
    "time" timestamp with time zone DEFAULT now() NOT NULL,
    usr_id bigint NOT NULL,
    ip character varying
);

CREATE TABLE usrh_name (
    usr_id bigint NOT NULL,
    name character varying NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY event
    ADD CONSTRAINT event_pkey PRIMARY KEY (project_id, ord);

ALTER TABLE ONLY project
    ADD CONSTRAINT project_pkey PRIMARY KEY (id);

ALTER TABLE ONLY usr
    ADD CONSTRAINT usr_confirmation_token_key UNIQUE (confirmation_token);

ALTER TABLE ONLY usr
    ADD CONSTRAINT usr_email_key UNIQUE (email);

ALTER TABLE ONLY usr
    ADD CONSTRAINT usr_pkey PRIMARY KEY (id);

ALTER TABLE ONLY usr
    ADD CONSTRAINT usr_reset_password_token_key UNIQUE (reset_password_token);

ALTER TABLE ONLY usr
    ADD CONSTRAINT usr_username_key UNIQUE (username);

ALTER TABLE ONLY usrd
    ADD CONSTRAINT usrd_pkey PRIMARY KEY (usr_id);

CREATE INDEX event_type_id_project_id_ord_idx ON event USING btree (type_id, project_id, ord);

CREATE INDEX project_usr_id_idx ON project USING btree (usr_id);

CREATE TRIGGER usr_login_stats_update AFTER INSERT ON usr_login_log FOR EACH ROW EXECUTE PROCEDURE usr_login_stats_update();

CREATE TRIGGER usrd_name_archive_trigger BEFORE UPDATE OF name ON usrd FOR EACH ROW WHEN (((old.name)::text <> (new.name)::text)) EXECUTE PROCEDURE archive_usrd_name();

ALTER TABLE ONLY event
    ADD CONSTRAINT event_project_id_fkey FOREIGN KEY (project_id) REFERENCES project(id);

ALTER TABLE ONLY project
    ADD CONSTRAINT project_usr_id_fkey FOREIGN KEY (usr_id) REFERENCES usr(id);

ALTER TABLE ONLY usrd
    ADD CONSTRAINT usrd_usr_id_fkey FOREIGN KEY (usr_id) REFERENCES usr(id);

ALTER TABLE ONLY usrh_name
    ADD CONSTRAINT usrh_name_usr_id_fkey FOREIGN KEY (usr_id) REFERENCES usr(id);

