#!/bin/sh

[ ! -e /etc/prometheus/prometheus.yml -a -z "$CONFIG" ] \
  && echo 'Config missing.' \
  && echo 'Provide either $CONFIG or /etc/prometheus/prometheus.yml' \
  && exit 1

[ -n "$CONFIG" ] && echo "$CONFIG" > /etc/prometheus/prometheus.yml
echo "----------------------------------------------------------------------------"
cat /etc/prometheus/prometheus.yml
echo "----------------------------------------------------------------------------"

[ -z "$LISTEN_ADDR" ] && LISTEN_ADDR=0.0.0.0:9091
[ -z "$EXTERNAL_URL" ] && EXTERNAL_URL=http://prometheus:9091/prometheus/biz/

CMD=/bin/prometheus
CMD="$CMD --config.file=/etc/prometheus/prometheus.yml"
CMD="$CMD --storage.tsdb.path=/data/"
CMD="$CMD --web.external-url=$EXTERNAL_URL"
CMD="$CMD --web.listen-address=$LISTEN_ADDR"

echo "> $CMD $@"
echo
exec $CMD "$@"