# Memory usage
-XX:MaxRAMPercentage=92.0

# Be specific about the GC we want
-XX:+UseG1GC

# Use Graal's JIT
-Dgraal.ShowConfiguration=verbose
-Dgraal.MitigateSpeculativeExecutionAttacks=None
-XX:+EagerJVMCI

# Useful for diagnostics
-XX:+PrintFlagsFinal
-XX:+UnlockDiagnosticVMOptions
-XshowSettings:vm
