# This will one day be enabled by default
-XX:+UnlockExperimentalVMOptions
-XX:+UseCGroupMemoryLimitForHeap

# All memory in container is for the JVM
-XX:MaxRAMFraction=1

# Prepare heap on startup rather than incrementally at runtime
-XX:+AlwaysPreTouch

# Default in Java 9, may as well use it now
-XX:+UseG1GC

# Useful for diagnostics
-XX:+PrintFlagsFinal
-XX:+UnlockDiagnosticVMOptions
-XX:+PrintActiveCpus
-XshowSettings:vm
