# Memory usage
-XX:MaxRAMPercentage=92.0

# Be specific about the GC we want
-XX:+UseG1GC

# Use Graal's JIT
-Dgraal.ShowConfiguration=verbose
-Dgraal.SpectrePHTBarriers=None
-XX:+UnlockExperimentalVMOptions
-XX:+EnableJVMCI
-XX:+EagerJVMCI

# On OOM
-XX:+ExitOnOutOfMemoryError

# Useful for diagnostics
-XX:+PrintFlagsFinal
-XX:+UnlockDiagnosticVMOptions
-XshowSettings:vm
