# ---------------------------------------
# Module: logging-logback
# Configure jetty logging to use Logback Logging.
# SLF4J is used as the core logging mechanism.
# See https://github.com/jetty-project/logging-modules/tree/master/logback
# ---------------------------------------

org.eclipse.jetty.util.log.class=org.eclipse.jetty.util.log.Slf4jLog

# Logback
--lib=webapps/ROOT/WEB-INF/lib/slf4j-api-*
--lib=webapps/ROOT/WEB-INF/lib/logback-*

# Logstash
--lib=webapps/ROOT/WEB-INF/lib/logstash-*
--lib=webapps/ROOT/WEB-INF/lib/jackson-*

# Prometheus
--lib=webapps/ROOT/WEB-INF/lib/simpleclient_logback*
--lib=webapps/ROOT/WEB-INF/lib/simpleclient_common*
--lib=webapps/ROOT/WEB-INF/lib/simpleclient-*
