--module=logging-logback

# Logback
jetty.webapp.addServerClasses+=,webapps/ROOT/WEB-INF/lib/slf4j-api-*
jetty.webapp.addServerClasses+=,webapps/ROOT/WEB-INF/lib/logback-*

# Logstash
jetty.webapp.addServerClasses+=,webapps/ROOT/WEB-INF/lib/logstash-*
jetty.webapp.addServerClasses+=,webapps/ROOT/WEB-INF/lib/jackson-*

# Prometheus
jetty.webapp.addServerClasses+=,webapps/ROOT/WEB-INF/lib/simpleclient_logback*
jetty.webapp.addServerClasses+=,webapps/ROOT/WEB-INF/lib/simpleclient_common*
jetty.webapp.addServerClasses+=,webapps/ROOT/WEB-INF/lib/simpleclient-*
