# --------------------------------------- 
# Module: websocket
# Enable websockets for deployed web applications
# --------------------------------------- 
--module=websocket

#org.eclipse.jetty.websocket.jsr356 = false