--module=logging
-Dorg.eclipse.jetty.util.log.class=org.eclipse.jetty.util.log.Slf4jLog

# Number of days to retain logs
jetty.log.retain=90


## Request Log Configuration
--module=requestlog
# How many days to retain the logs
jetty.requestlog.retain=90
# If an existing log with the same name is found, just append to it
jetty.requestlog.append=true
# Use the extended log output
jetty.requestlog.extended=true
# Log http cookie information as well
jetty.requestlog.cookies=false
# Set the log output timezone
jetty.requestlog.timezone=Australia/Sydney

