# Reference YML available at:
#   https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-reference-yml.html

filebeat.autodiscover:
  providers:

  ######################################################################################################################
  # Shipreq: webapp
  - type: docker
    templates:
    - condition:
        contains:
          docker.container.name: webapp
      config:
      - type: container
        paths:
          - /var/lib/docker/containers/${data.docker.container.id}/*-json.log
        encoding: utf-8
        json.keys_under_root: true
        json.add_error_key: true
        json.message_key: message
        # processors:
        # - add_docker_metadata: ~
        processors:
        - add_fields:
            target: ''
            fields:
              '@service': 'shipreq/webapp' # Ensure that non-JSON lines are tagged too

  ######################################################################################################################
  # Shipreq: taskman
  - type: docker
    templates:
    - condition:
        contains:
          docker.container.name: taskman
      config:
      - type: container
        paths:
          - /var/lib/docker/containers/${data.docker.container.id}/*-json.log
        encoding: utf-8
        json.keys_under_root: true
        json.add_error_key: true
        json.message_key: message
        # processors:
        # - add_docker_metadata: ~
        processors:
        - add_fields:
            target: ''
            fields:
              '@service': 'shipreq/taskman' # Ensure that non-JSON lines are tagged too

  ######################################################################################################################
  # Prometheus

  - type: docker
    templates:
    - condition:
        contains:
          docker.container.name: prometheus-tech
      config:
      - type: container
        paths:
          - /var/lib/docker/containers/${data.docker.container.id}/*-json.log
        encoding: utf-8
        processors:
        - add_fields:
            target: ''
            fields:
              '@service': 'ops/prometheus-tech'
        - rename:
            fields:
             - from: message
               to: original_message
        - dissect:
            tokenizer: "level=%{level} ts=%{?ts} caller=%{logger_name} %{?other}msg=\"%{message}\""
            field: original_message
            target_prefix: ''

  - type: docker
    templates:
    - condition:
        contains:
          docker.container.name: prometheus-biz
      config:
      - type: container
        paths:
          - /var/lib/docker/containers/${data.docker.container.id}/*-json.log
        encoding: utf-8
        processors:
        - add_fields:
            target: ''
            fields:
              '@service': 'ops/prometheus-biz'
        - rename:
            fields:
             - from: message
               to: original_message
        - dissect:
            tokenizer: "level=%{level} ts=%{?ts} caller=%{logger_name} %{?other}msg=\"%{message}\""
            field: original_message
            target_prefix: ''

  ######################################################################################################################
  # node_exporter
  - type: docker
    templates:
    - condition:
        contains:
          docker.container.name: node_exporter
      config:
      - type: container
        paths:
          - /var/lib/docker/containers/${data.docker.container.id}/*-json.log
        encoding: utf-8
        processors:
        - add_fields:
            target: ''
            fields:
              '@service': 'ops/node_exporter'
        - rename:
            fields:
             - from: message
               to: original_message
        - dissect:
            tokenizer: "time=\"%{?time}\" level=%{level} msg=\"%{message}\" source=\"%{logger_name}\"%{?other}"
            field: original_message
            target_prefix: ''

  ######################################################################################################################
  # postgres_exporter
  - type: docker
    templates:
    - condition:
        contains:
          docker.container.name: postgres_exporter
      config:
      - type: container
        paths:
          - /var/lib/docker/containers/${data.docker.container.id}/*-json.log
        encoding: utf-8
        processors:
        - add_fields:
            target: ''
            fields:
              '@service': 'ops/postgres_exporter'
        - rename:
            fields:
             - from: message
               to: original_message
        - dissect:
            tokenizer: "time=\"%{?time}\" level=%{level} msg=\"%{message}\" source=\"%{logger_name}\"%{?other}"
            field: original_message
            target_prefix: ''

  ######################################################################################################################
  # cadvisor
  - type: docker
    templates:
    - condition:
        contains:
          docker.container.name: cadvisor
      config:
      - type: container
        paths:
          - /var/lib/docker/containers/${data.docker.container.id}/*-json.log
        encoding: utf-8
        processors:
        - add_fields:
            target: ''
            fields:
              '@service': 'ops/cadvisor'
        - rename:
            fields:
             - from: message
               to: original_message
        - dissect:
            tokenizer: "%{?crap}       %{?n} %{logger_name}] %{message}"
            field: original_message
            target_prefix: ''

  ######################################################################################################################
  # grafana
  - type: docker
    templates:
    - condition:
        contains:
          docker.container.name: grafana
      config:
      - type: container
        paths:
          - /var/lib/docker/containers/${data.docker.container.id}/*-json.log
        encoding: utf-8
        processors:
        - add_fields:
            target: ''
            fields:
              '@service': 'ops/grafana'
        - rename:
            fields:
             - from: message
               to: original_message
        - dissect:
            tokenizer: "t=%{?t} lvl=%{level} msg=\"%{message}\""
            field: original_message
            target_prefix: ''

output.elasticsearch:
  hosts: '${ES_HOSTS}'
  index: "filebeat-%{+yyyy.MM.dd}"
  compression_level: ${ES_COMPRESSION_LEVEL:3}
  ssl.verification_mode: ${ES_SSL_VERIFICATION_MODE:full}

# This alone doesn't actually create the index in ElasticSearch (or at least in Kibana)
# but it's required because output.elasticsearch.index is specified above
setup.template:
  name: "filebeat"
  pattern: "filebeat-*"

# output.console:
#   enabled: true
#   pretty: true
