#!/bin/bash

[ -z "$AWS_INSTANCE_ID" ] && export AWS_INSTANCE_ID="$(curl -s http://169.254.169.254/latest/meta-data/instance-id)"
[ -z "$AWS_INSTANCE_IP" ] && export AWS_INSTANCE_IP="$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)"

set -euo pipefail

echo "AWS_INSTANCE_ID = $AWS_INSTANCE_ID"
echo "AWS_INSTANCE_IP = $AWS_INSTANCE_IP"
echo "CLUSTER         = $CLUSTER"
echo "ES_HOSTS        = $ES_HOSTS"

echo "> filebeat $@"
exec filebeat "$@"