#!/bin/bash
cd "$(dirname "$(readlink -e "$0")")" || exit 1
[ -z "$GCP_PROJECT" ] && echo "Use ./target to target an environment first." && exit 1
set -e

./cluster-login

kubectl apply -f <(echo "
$(envsubst < cluster-cloudsqlproxy.yml)
")
