apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: cloudsqlproxy
spec:
  template:
    metadata:
      labels:
        app: cloudsqlproxy
    spec:
      containers:
      - name: cloudsqlproxy
        # https://github.com/GoogleCloudPlatform/cloudsql-proxy/releases
        image: gcr.io/cloudsql-docker/gce-proxy:1.10
        command:
        - "/cloud_sql_proxy"
        - "--dir=/cloudsql"
        - "-instances=$GCP_PROJECT:$GCP_REGION:$DB_INSTANCE=tcp:0.0.0.0:5432"
        - "-credential_file=/secrets/cloudsql/credentials.json"
        ports:
        - name: sql-port
          containerPort: 5432
        volumeMounts:
          - name: cloudsql-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
          - name: cloudsql
            mountPath: /cloudsql
          - name: ssl-certs
            mountPath: /etc/ssl/certs

      volumes:
      - name: cloudsql-credentials
        secret:
          secretName: cloudsql-credentials
      - name: cloudsql
        emptyDir:
      - name: ssl-certs
        hostPath:
          path: /etc/ssl/certs
---
apiVersion: v1
kind: Service
metadata:
  name: $SERVICE_DBPROXY
spec:
  selector:
    app: cloudsqlproxy
  ports:
  - port: 5432
    targetPort: sql-port
