apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: webapp
    spec:
      containers:

      - name: webapp
        image: "$GCP_GCR_IO/$GCP_PROJECT/webapp:latest"
        imagePullPolicy: Always
        env:
        - name: db_host
          value: $SERVICE_DBPROXY
        - name: shipreq_url
          value: https://dev.shipreq.com
        - name: EXTERNAL_PORT_SSL
          value: "443"
        - name: RUN_MODE
          value: staging
        resources:
          requests:
            memory: "1300Mi"
          limits:
            memory: "1856Mi"
        ports:
        - containerPort: 8080
        - containerPort: 8443
        livenessProbe:
          httpGet:
            path: /ops/ok
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 40
          timeoutSeconds: 2
        volumeMounts:
        - name: webapp-props
          mountPath: /shipreq/conf
        # - name: webapp-secrets
        #   mountPath: /shipreq/secrets1
        - name: db-props
          mountPath: /shipreq/secrets2

      volumes:
      - name: webapp-props
        configMap:
          name: webapp-props
      # - name: webapp-secrets
      #   secret:
      #     secretName: webapp-secrets
      - name: db-props
        secret:
          secretName: db-props

---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  selector:
    name: webapp
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 443
    targetPort: 8443
    protocol: TCP
