apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: taskman
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: taskman
    spec:
      containers:

      - name: taskman
        image: "$GCP_GCR_IO/$GCP_PROJECT/taskman:latest"
        imagePullPolicy: Always
        env:
        - name: db_host
          value: $SERVICE_DBPROXY
        resources:
          requests:
            cpu: "0.3"
            memory: "365Mi"
          limits:
            cpu: "0.5"
            memory: "448Mi"
        livenessProbe:
          exec:
            command:
            - /taskman/bin/healthcheck
            - /taskman/taskman.lives
          initialDelaySeconds: 60
          periodSeconds: 60
        volumeMounts:
        - name: taskman-props
          mountPath: /taskman/conf
        # - name: taskman-secrets
        #   mountPath: /taskman/secrets1
        - name: db-props
          mountPath: /taskman/secrets2

      volumes:
      - name: taskman-props
        configMap:
          name: taskman-props
      # - name: taskman-secrets
      #   secret:
      #     secretName: taskman-secrets
      - name: db-props
        secret:
          secretName: db-props
