#!/bin/bash
cd "$(dirname "$(readlink -e "$0")")" || exit 1
[ -z "$GCP_PROJECT" ] && echo "Use ./target to target an environment first." && exit 1
[ -e $KUBECONFIG ] || $gcloud container clusters get-credentials $CLUSTER_NAME --zone $GCP_ZONE
