#!/bin/bash
cd "$(dirname "$(readlink -e "$0")")" || exit 1
[ -z "$GCP_PROJECT" ] && echo "Use ./target to target an environment first." && exit 1

set -e

function log { echo -e "\033[1;33m$*\033[0m" ;}

# Ensure pwgen installed
pwgen 16 1 >/dev/null

log "Logging Kubernetes into cluster..."

./cluster-login

log "Creating service account key..."

$gcloud iam service-accounts keys create $ENVTMP/$ACCT_APPSQL-key.json --iam-account $ACCT_APPSQL@$GCP_PROJECT.iam.gserviceaccount.com

kubectl create secret generic cloudsql-credentials --from-file=credentials.json=$ENVTMP/$ACCT_APPSQL-key.json

log "Creating DB account..."

DB_PASSWORD=$(pwgen 64 1)

$gcloud sql users create $DB_USERNAME host --instance=$DB_INSTANCE --password=$DB_PASSWORD

echo "
db.database = shipreq
db.username = $DB_USERNAME
db.password = $DB_PASSWORD
" > $ENVTMP/secret-db.properties

kubectl create secret generic db-props --from-file=db.properties=$ENVTMP/secret-db.properties

log "Done."
