#!/bin/bash
cd "$(dirname "$(readlink -e "$0")")" || exit 1
[ -n "$GCP_PROJECT" ] && echo "You're already targetting an environment: $GCP_PROJECT" && exit 1
[ $# -ne 1 ] && echo "Usage: $0 <dev | prod>" && exit 1
c="$1/config.props"
[ ! -e "$c" ] && echo "Invalid environment: $1" && exit 1
echo "Preparing a new shell to target $1..."

tmp=/tmp/shipreq-env-$(date +%Y%m%d-%H%M%S)-$$
mkdir $tmp
chmod 700 $tmp

OLDDOTDIR="$ZDOTDIR"
[ -z "$OLDDOTDIR" ] && OLDDOTDIR="$HOME"
for f in .zshenv .zprofile .zshrc .zlogin .zlogout; do
  [ -e "$OLDDOTDIR/$f" ] && cp -p "$OLDDOTDIR/$f" $tmp
done
cfg="$(sed '/^ *$/d' $c | perl -pe 's/ *= */=/')"
echo "$cfg" | perl -pe 's/^/export /'                >> $tmp/.zshenv
echo "$cfg" | perl -pe 's/^/export TF_VAR_/'         >> $tmp/.zshenv
echo "export ENVNAME=$1"                             >> $tmp/.zshenv
echo "export ENVTMP=$tmp"                            >> $tmp/.zshenv
echo "export KUBECONFIG=$tmp/kube-config"            >> $tmp/.zshenv
echo 'export gcloud="gcloud --project $GCP_PROJECT"' >> $tmp/.zshenv
echo 'export PROMPT="[$GCP_PROJECT] $PROMPT"'        >> $tmp/.zshrc
echo 'alias gcloud="$gcloud"'                        >> $tmp/.zshrc
echo 'alias k=kubectl'                               >> $tmp/.zshrc

ZDOTDIR=$tmp zsh -i

rm -rf $tmp
