#!/bin/bash
cd "$(dirname "$(readlink -e "$0")")" || exit 1
[ -z "$GCP_PROJECT" ] && echo "Use ./target to target an environment first." && exit 1

bucket=shipreq-$ENVNAME-terraform

# Create storage bucket if it doesn't already exist
gsutil ls -p $GCP_PROJECT gs://$bucket/ &>/dev/null \
  || gsutil mb -p $GCP_PROJECT gs://$bucket/

terraform init -backend-config=bucket=$bucket
