#!/bin/bash
set -euo pipefail
#cd "$(dirname "$0")" || exit 1
#cd "$(dirname "$(readlink -e "$0")")" || exit 1
#[ $# -ne 1 ] && echo "Usage: $0 <xxx>" && exit 1
#tmp=/tmp/$(date +%Y%m%d-%H%M%S)-$$

d=$(dirname "$1")
w=../webapp-base-test

mkdir -p $w/$d
mv "$1" $w/"$1"
