#!/bin/bash

mkdir -p /is \
  && mkfs.ext4 -O ^has_journal,dir_index,sparse_super,uninit_bg /dev/xvdb \
  && uuid=$(lsblk -f  | fgrep 'xvdb ' | awk '{print $3}') \
  && echo "UUID=$uuid  /is  ext4  rw,noatime  0 0" >> /etc/fstab \
  && mount /is \
  && df -h

