#!/bin/bash

[ -z "$1" ] && echo "Usage: $0 <public DNS>" && exit 1

cd "$(dirname "$0")"

rsync -vzrRlptSihOJ --skip-compress=jar \
  --exclude={demo-base,log,work,'*.war','.*.sw?',production.golly.props} \
  jetty-9.1.0 webapp $(<username)@"$1":

