ALTER TABLE event DROP CONSTRAINT event_seq_check;
ALTER TABLE event ADD CONSTRAINT event_ord_check CHECK (ord > 0);

ALTER TABLE project ADD COLUMN init_events SMALLINT NULL CHECK (init_events >= 0);
COMMENT ON COLUMN project.init_events IS 'The number of synthetic events generated by ShipReq (not the user directly) when the project was created.';
UPDATE project SET init_events = 2;
ALTER TABLE project ALTER COLUMN init_events SET NOT NULL;
