ALTER TABLE event DROP CONSTRAINT event_seq_check;
ALTER TABLE event ADD CONSTRAINT event_ord_check CHECK (ord > 0);

ALTER TABLE project ADD COLUMN init_events SMALLINT NULL CHECK (init_events >= 0);
COMMENT ON COLUMN project.init_events IS 'The number of synthetic events generated by ShipReq (not the user directly) when the project was created.';
UPDATE project SET init_events = 2;
ALTER TABLE project ALTER COLUMN init_events SET NOT NULL;

------------------------------------------------------------------------------------------------------------------------
--CREATE TABLE tmp2 AS
--select project_id, ord+1 ord, scope, logic_ver, hash_scheme, hash from event_hash;
--
--CREATE TABLE tmp1 AS
--SELECT project_id, ord+1 ord, type_id, data_id, data_id_type, data, created_at from event;
--
--select (select count(1) from tmp1) as tmp1, (select count(1) from tmp2) as tmp2;
--
--truncate event_hash cascade;
--delete from event;
--
--select (select count(1) from event) as event, (select count(1) from event_hash) as event_hash;
--
--insert into event select * from tmp1;
--insert into event_hash select * from tmp2;
--
--select (select count(1) from event) as event, (select count(1) from event_hash) as event_hash;
--
--drop table tmp1;
--drop table tmp2;