#!/bin/bash
cd $(dirname "$0")

S=shipreq
tail="less -S +F '-Pw%f '"

function latest {
  dir="$1"
  pat="$2"
  ls -r1t "$dir/" | grep "$pat" | tail -1 | sed "s!^!$dir/!"
}

tmux -2 new-session -d -s $S \
  && tmux rename-window logs \
  && tmux split-window -v -d \
  && tmux resize-pane -U 999 && tmux resize-pane -D 13 \
  && tmux split-window -v -t 1 \
  && tmux split-window -v -t 0 -l 10 \
  && tmux select-pane -t 0 && tmux send-keys "clear; $tail $(latest webapp/log \^jetty)" C-m \
  && tmux select-pane -t 2 && tmux send-keys "clear; $tail $(latest webapp/log \^access)" C-m \
  && tmux select-pane -t 3 && tmux send-keys "clear; $tail webapp/log/webapp.log" C-m \
  && tmux select-pane -t 1 && tmux send-keys "clear; $tail taskman/log/taskman.log" C-m

#tmux select-window -t $S:0
tmux -2 attach-session -t $S

