db.pool.maximumPoolSize                               = 4
redis.connectionMinimumIdleSize                       = 1
redis.connectionPoolSize                              = 4
redis.subscriptionConnectionPoolSize                  = 4
shipreq.feature.publicRegistration                    = true
shipreq.statcounter.project                           = 12198830
shipreq.statcounter.security                          = 7b5d1ebe
shipreq.googleAnalytics.trackingId                    = UA-105581783-2
shipreq.jaeger.enabled                                = false
shipreq.security.jwt.cookie.secure                    = false
shipreq.security.jwt.lifespan                         = 7 days
shipreq.security.jwt.secret                           = ....:....1....:....2....:....3....:....4....:....5....:....6....
shipreq.security.verification_token.length            = 49
shipreq.security.verification_token.lifespan.register = 3 days
shipreq.security.verification_token.lifespan.resetpw  = 24 hours
shipreq.taskman.init.retry.delay                      = 3 sec
shipreq.taskman.schema                                = taskman
shipreq.security.hack.project_access                  = {"5":[6]}
# shipreq.ssr.enabled = false