#!/bin/bash

source $(dirname "$0")/lib.sh
lookup1 "$@"

fix_fks=$("$dbdir"/fix-fk_ids_in_dump "$1")
[ ! -x "$fix_fks" ] && echo "Failed: fix-fk_ids_in_dump" && exit 1

f1="$dbdir"/dump-$1.sql
f2="$dbdir"/dump-$1-d.sql
dump="$sudo_pg_dump --blobs"

echo "Dump #1..." \
  && $dump --clean --create $db > "$f1" \
  && echo && echo "Dump #2..." \
  && $dump --data-only --column-inserts --disable-triggers $db | $fix_fks > "$f2" \
  && echo && ls -l "$f1" "$f2"
