#!/bin/bash

dbdir="$(dirname "$0")"

case "$1" in
  dev)  db=usecase_dev ;;
  test) db=usecase_test ;;
  prod) db=usecase_prod ;;
  *) echo -e "Unknown db: '$1'.\nExpected [dev|test|prod]." >&2; exit 1
esac

fix_fks=$("$dbdir"/fix-fk_ids_in_dump "$1")
[ ! -x "$fix_fks" ] && echo "Failed: fix-fk_ids_in_dump" && exit 1

f1="$dbdir"/dump-$1.sql
f2="$dbdir"/dump-$1-d.sql
dump="sudo -u postgres pg_dump --encoding=UTF-8 --blobs"

echo "Dump #1..." \
  && $dump --clean --create $db > "$f1" \
  && echo && echo "Dump #2..." \
  && $dump --data-only --column-inserts --disable-triggers $db | $fix_fks > "$f2" \
  && echo && ls -l "$f1" "$f2"
