#!/bin/bash
#cd "$(dirname "$0")"
#[ -z "$1" ] && echo "Usage: $0 <xxx>" && exit 1
#tmp=/tmp/$(date +%Y%m%d-%H%M%S)-$$
#xxx="$(cd "$(dirname "$0")/xxx" && pwd)"

tmp=/tmp/hehe
dump=$tmp/dump.sql
# pg_dump --encoding=UTF-8 --data-only --no-owner --no-privileges --no-tablespaces usecase_prod > $dump
dump=/tmp/dumped

tables=(
  schema_version
  field_key
  field_key_type

  usr
  project

  usecase
  usecase_rev
  text
  text_rev
  uc_field

  share

  usr_login_log
  share_view_log
)
IFS=$'\n' sorted_tables=($(sort <<<"${tables[*]}"))

# Make sure all tables are accounted for
actual_tables="$(grep '^COPY .* (' $dump | awk '{print $2}' | sort | xargs)"
if [[ "$actual_tables" != "${sorted_tables[@]}" ]]; then
  echo "Table list differs."
  echo "Known tables:  ${sorted_tables[@]}"
  echo "Actual tables: $actual_tables"
  exit 2
fi

for t in "${tables[@]}"; do
  echo
  x="$( sed '/^COPY '$t' (.*/,/^\\\.$/!d' $dump )"
  copy_cmds_found="$(grep '^COPY .* (' <<<"$x" | wc -l)"
  [ "$copy_cmds_found" -ne 1 ] \
    && echo "ERROR: Extraction of $t produced $copy_cmds_found COPY commands. (Expected: 1)" \
    && exit 1
  echo "$x"
done
