db.appname                         = TASKMAN
db.schema                          = taskman
db.pool.maximumPoolSize            = 8

supportDesk.via                    = mail
supportDesk.mail.from              = dev@shipreq.com
supportDesk.mail.to                = dev@shipreq.com

# supportDesk.via                    = freshdesk
# freshdesk.domain                   = blah
# freshdesk.key                      = aaaaaaaaaaaaaaaaaaaa
# freshdesk.taskmanEmail             = Taskman <taskman@shipreq.com>
# freshdesk.org.landingPage          = Sales / Lead
# freshdesk.org.failure              = QA / Incident
# freshdesk.org.userFeedback         = Product Management / Feedback

mail.concurrency.max               = 4
mail.public.from                   = dev@shipreq.com
mail.via                           = no-op

# mail.via                           = mailgun
# mailgun.domain                     = mg.shipreq.com
# mailgun.apiKey                     = aaaaaaaaaaaaaaaa
# mailgun.tags                       = dev

# mail.via                           = javamail
# mail.smtp.host                     = smtp.gmail.com
# mail.smtp.socketFactory.port       = 465
# mail.smtp.socketFactory.class      = javax.net.ssl.SSLSocketFactory
# mail.smtp.ssl.enable               = true
# mail.smtp.auth                     = true
# mail.smtp.port                     = 465
# mail.user                          = username
# mail.password                      = aaaaaaaaaaaaaaaa

mailingList.via                    = no-op

# mailingList.via                    = mailchimp
# mailchimp.dc                       = us8
# mailchimp.key                      = aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-us8
# mailchimp.audienceId               = 1234567890

shipreq.schema                     = public

taskman.poll.every                 = 5 sec
taskman.poll.gap                   = 1 sec
taskman.queueSize                  = 10
taskman.remoteCfg.retry.delay      = 3 sec
taskman.trustPeriod                = 1 min
taskman.healthFile                 = /tmp/taskman-dev.health
