db.appname                         = TASKMAN
db.schema                          = taskman
db.pool.maximumPoolSize            = 8

freshdesk.domain                   = yoarmum
freshdesk.key                      = 6nOvQN6fH4XKlVCbXHD9
freshdesk.taskmanEmail             = Taskman <taskman@shipreq.com>
freshdesk.org.landingPage          = Sales / Lead
freshdesk.org.failure              = QA / Incident
freshdesk.org.userFeedback         = Product Management / Feedback

mail.concurrency.max               = 4
mail.public.from                   = local-test@shipreq.com
mail.archive.to                    = japgolly+test_taskman_archive@gmail.com

# Ensure [Allow less secure apps] is enabled in Gmail
# https://support.google.com/accounts/answer/6010255
mail.via                           = javamail
mail.smtp.host                     = smtp.gmail.com
mail.smtp.socketFactory.port       = 465
mail.smtp.socketFactory.class      = javax.net.ssl.SSLSocketFactory
mail.smtp.ssl.enable               = true
mail.smtp.auth                     = true
mail.smtp.port                     = 465
mail.user                          = yoar.mum@gmail.com
mail.password                      = 6vJDhVXYm8G95uXj3gPq

# mail.via                           = mailgun
# mailgun.domain                     = mg.shipreq.com
# mailgun.apiKey                     = xxxxx
# mailgun.tags                       = dev

mailchimp.dc                       = us8
mailchimp.key                      = d96852e88497f5dd2d19da53fc565236-us8
mailchimp.masterList               = Master

shipreq.schema                     = public

taskman.poll.every                 = 5 sec
taskman.poll.gap                   = 1 sec
taskman.queueSize                  = 10
taskman.remoteCfg.retry.delay      = 3 sec
taskman.trustPeriod                = 1 min
taskman.healthFile                 = /tmp/taskman-dev.health
