{
 "title": "Business (managed)",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "user_type", "query": "public,staff" }
  ]
 },
 "panels": [
  {
   "title": "Users",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (registered) (avg_over_time(shipreq_users_total{user_type=~\"$user_type\"}[$__interval]))",
     "legendFormat": "registered={{registered}}"
    }
   ]
  },
  {
   "title": "Projects",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(shipreq_projects_total{owner_type=~\"$user_type\"}[$__interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Events",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(shipreq_events_total{owner_type=~\"$user_type\",initial=\"n\"}[$__interval]))",
     "legendFormat": "user"
    }
   ]
  },
  {
   "title": "Reqs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (avg_over_time(shipreq_reqs_total{owner_type=~\"$user_type\",live=\"n\"}[$__interval]))",
     "legendFormat": "dead"
    },
    {
     "expr": "sum (avg_over_time(shipreq_reqs_total{owner_type=~\"$user_type\",live=\"y\"}[$__interval]))",
     "legendFormat": "live"
    },
    {
     "expr": "sum (avg_over_time(shipreq_reqs_total{owner_type=~\"$user_type\"}[$__interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Logins / Day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(shipreq_daily_logins_total{user_type=~\"$user_type\",unique_user=\"n\"}[$__interval])",
     "legendFormat": "total"
    },
    {
     "expr": "sum(max_over_time(shipreq_daily_logins_total{user_type=~\"$user_type\",unique_user=\"y\"}[$__interval]))",
     "legendFormat": "unique"
    }
   ]
  },
  {
   "title": "Project Access / Day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(shipreq_daily_project_reads_total{owner_type=~\"$user_type\",access=\"rw\",unique_project=\"n\"}[$__interval])",
     "legendFormat": "total"
    },
    {
     "expr": "sum(max_over_time(shipreq_daily_project_reads_total{owner_type=~\"$user_type\",access=\"rw\",unique_project=\"y\"}[$__interval]))",
     "legendFormat": "unique"
    }
   ]
  },
  {
   "title": "Time since Last Login",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(shipreq_users_last_login_seconds_ago{user_type=~\"$user_type\"}[$__interval])",
     "legendFormat": "p{{p}}"
    }
   ]
  },
  {
   "title": "Time since Project Access",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(shipreq_project_last_access_seconds_ago{owner_type=~\"$user_type\",access=\"rw\"}[$__interval])",
     "legendFormat": "p{{p}}"
    }
   ]
  }
 ]
}