{
 "title": "Health Now (managed)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "interval", "query": "1m" },
   { "name": "security_window", "query": "5m,15m,30m,1h,2h,4h" }
  ]
 },
 "panels": [
  {
   "title": "In Production For",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "max",
   "targets": [
    { "expr": "time() - 1575710173" }
   ]
  },
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count (node_exporter_build_info)"
    }
   ]
  },
  {
   "title": "Clusters",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "ecs_clusters" }
   ]
  },
  {
   "title": "Services",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(ecs_services)" }
   ]
  },
  {
   "title": "Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count (container_start_time_seconds{ecs_name=~\".+\"})"
    }
   ]
  },
  {
   "title": "Services",
   "type": "table",
   "gridPos": { "h": 16, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum(label_replace(count(container_start_time_seconds{ecs_name=~\".+\"}) by (ecs_name), \"service\", \"$1\", \"ecs_name\", \"(.*)\") or (ecs_service_desired_tasks * 0)) by (service)",
     "legendFormat": "up"
    },
    {
     "expr": "sum(ecs_service_desired_tasks) by (service)",
     "legendFormat": "desired"
    },
    {
     "expr": "(sum(label_replace(count(container_start_time_seconds{ecs_name=~\".+\"}) by (ecs_name), \"service\", \"$1\", \"ecs_name\", \"(.*)\") or (ecs_service_desired_tasks * 0)) by (service)) / on (service) (sum(ecs_service_desired_tasks) by (service))",
     "legendFormat": "up %"
    }
   ]
  },
  {
   "title": "Clusters",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum by (cluster) (ecs_container_instances)",
     "legendFormat": "nodes"
    },
    {
     "expr": "sum by (cluster) (ecs_services)",
     "legendFormat": "services"
    },
    {
     "expr": "sum(label_replace(count(container_start_time_seconds{ecs_name=~\".+\"}) by (ecs_cluster), \"cluster\", \"$1\", \"ecs_cluster\", \"(.*)\") or (ecs_service_desired_tasks * 0)) by (cluster)",
     "legendFormat": "c up"
    },
    {
     "expr": "sum(ecs_service_desired_tasks) by (cluster)",
     "legendFormat": "c desired"
    },
    {
     "expr": "(sum(label_replace(count(container_start_time_seconds{ecs_name=~\".+\"}) by (ecs_cluster), \"cluster\", \"$1\", \"ecs_cluster\", \"(.*)\") or (ecs_service_desired_tasks * 0) or label_replace(count(container_start_time_seconds{ecs_name=~\".+\"}), \"cluster\", \"total\", \"\", \"\")) by (cluster)) / on (cluster) (sum(ecs_service_desired_tasks) by (cluster))",
     "legendFormat": "c up %"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count by (ecs_cluster, instance) (container_memory_usage_bytes{ecs_cluster=~\".+\"})"
    },
    {
     "expr": "node_load1 / on(instance) (count (node_cpu_seconds_total{mode=\"idle\"}) by (instance))",
     "legendFormat": "cpu1"
    },
    {
     "expr": "node_load5 / on(instance) (count (node_cpu_seconds_total{mode=\"idle\"}) by (instance))",
     "legendFormat": "cpu5"
    },
    {
     "expr": "node_load15 / on(instance) (count (node_cpu_seconds_total{mode=\"idle\"}) by (instance))",
     "legendFormat": "cpu15"
    },
    {
     "expr": "1 - ((node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes) / node_memory_MemTotal_bytes)",
     "legendFormat": "mem"
    },
    {
     "expr": "node_filefd_allocated / node_filefd_maximum",
     "legendFormat": "fds"
    },
    {
     "expr": "sum(\n  increase(node_network_receive_errs_total[$interval]) +\n  increase(node_network_transmit_errs_total[$interval]) +\n  increase(node_network_receive_drop_total[$interval]) +\n  increase(node_network_transmit_drop_total[$interval])\n) by (instance)",
     "legendFormat": "net"
    },
    {
     "expr": "node_time_seconds - on(instance) node_boot_time_seconds",
     "legendFormat": "uptime"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "(count by (instance,mountpoint) (node_filesystem_size_bytes{fstype!~\"tmpfs|efivarfs\"})) * on(instance) group_left(ecs_cluster) (count by (ecs_cluster, instance) (container_memory_usage_bytes{ecs_cluster=~\".+\"}) * 0)"
    },
    {
     "expr": "node_filesystem_size_bytes{fstype!~\"tmpfs|efivarfs\"} - node_filesystem_free_bytes"
    },
    {
     "expr": "node_filesystem_size_bytes{fstype!~\"tmpfs|efivarfs\"}"
    },
    {
     "expr": "1 - node_filesystem_free_bytes{fstype!~\"tmpfs|efivarfs\"} / node_filesystem_size_bytes"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "table",
   "gridPos": { "h": 20, "w": 10, "x": 14, "y": 16 },
   "targets": [
    {
     "expr": "sum by (id, instance, ecs_name) (irate(container_cpu_cfs_throttled_seconds_total{ecs_name=~\".+\"}[$interval]) or (container_memory_working_set_bytes{ecs_name=~\".+\"} * 0))",
     "legendFormat": "cpu"
    },
    {
     "expr": "sum by (id, instance, ecs_name) (container_memory_working_set_bytes{ecs_name=~\".+\"})",
     "legendFormat": "mem"
    },
    {
     "expr": "(sum(container_memory_working_set_bytes{ecs_name=~\".+\"}) by (id, instance, ecs_name))\n/\n# Below we use the container memory hard-limit if set, else (container.memUsed + node.memUsable)\n(\n  ((sum(container_spec_memory_limit_bytes{ecs_name=~\".+\"}) by (id, instance, ecs_name)) > 0)\n  or (\n    (\n      ((sum(container_spec_memory_limit_bytes{ecs_name=~\".+\"}) by (id, instance, ecs_name)) == 0) +\n      (sum(container_memory_working_set_bytes{ecs_name=~\".+\"}) by (id, instance, ecs_name))\n    ) + on(instance) group_left () (\n      node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes\n    )\n  )\n)",
     "legendFormat": "mem %"
    },
    {
     "expr": "time() - max by (id, instance, ecs_name) (container_start_time_seconds{ecs_name=~\".+\"})",
     "legendFormat": "uptime"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by (job) (increase(logback_appender_total{level=~\"[iI].+\"}[$security_window]))"
    },
    {
     "expr": "sum by (job) (increase(logback_appender_total{level=~\"[wW].+\"}[$security_window]))"
    },
    {
     "expr": "sum by (job) (increase(logback_appender_total{level=~\"[eEfF].+\"}[$security_window]))"
    }
   ]
  },
  {
   "title": "Secure Events",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(shipreq_webapp_secure_events_total[$security_window]) or (0 * cadvisor_version_info))"
    }
   ]
  }
 ]
}