{
 "title": "Health Past (managed)",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30m",
 "panels": [
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node CPU (1m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(node_load1 / on(instance) (count (node_cpu_seconds_total{mode=\"idle\"}) by (instance)))\n+ on(instance) group_left(ecs_cluster)\n(count by (ecs_cluster, instance) (container_memory_usage_bytes{ecs_cluster=~\".+\"}) * 0)",
     "legendFormat": "{{ecs_cluster}}:{{instance}}"
    }
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(1 - ((node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes) / node_memory_MemTotal_bytes))\n+ on(instance) group_left(ecs_cluster)\n(count by (ecs_cluster, instance) (container_memory_usage_bytes{ecs_cluster=~\".+\"}) * 0)",
     "legendFormat": "{{ecs_cluster}}:{{instance}}"
    }
   ]
  },
  {
   "title": "Node CPU (15m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(node_load15 / on(instance) (count (node_cpu_seconds_total{mode=\"idle\"}) by (instance)))\n+ on(instance) group_left(ecs_cluster)\n(count by (ecs_cluster, instance) (container_memory_usage_bytes{ecs_cluster=~\".+\"}) * 0)",
     "legendFormat": "{{ecs_cluster}}:{{instance}}"
    }
   ]
  },
  {
   "title": "Node Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(node_time_seconds - on(instance) node_boot_time_seconds)\n+ on(instance) group_left(ecs_cluster)\n(count by (ecs_cluster, instance) (container_memory_usage_bytes{ecs_cluster=~\".+\"}) * 0)",
     "legendFormat": "{{ecs_cluster}}:{{instance}}"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Container Uptime",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "min by (ecs_name) (time() - max by (id, instance, ecs_name) (container_start_time_seconds{ecs_name=~\".+\"}))",
     "legendFormat": "{{ecs_name}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max by (ecs_name) (\n  (sum(container_memory_working_set_bytes{ecs_name=~\".+\"}) by (id, instance, ecs_name))\n  /\n  # Below we use the container memory hard-limit if set, else (container.memUsed + node.memUsable)\n  (\n    ((sum(container_spec_memory_limit_bytes{ecs_name=~\".+\"}) by (id, instance, ecs_name)) > 0)\n    or (\n      (\n        ((sum(container_spec_memory_limit_bytes{ecs_name=~\".+\"}) by (id, instance, ecs_name)) == 0) +\n        (sum(container_memory_working_set_bytes{ecs_name=~\".+\"}) by (id, instance, ecs_name))\n      ) + on(instance) group_left () (\n        node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes\n      )\n    )\n  )\n)",
     "legendFormat": "{{ecs_name}}"
    }
   ]
  },
  { "title": "Apps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Logs (WARN)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job,level) (increase(logback_appender_total{level=~\"[wW].*\"}[$__interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Logs (ERROR / FATAL)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job,level) (increase(logback_appender_total{level=~\"[eEfF].*\"}[$__interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(shipreq_webapp_http_response_duration_seconds_count{type!=\"ops\"}[$__interval]))",
     "legendFormat": "http (public)"
    },
    {
     "expr": "sum(increase(shipreq_webapp_ws_open[$__interval]))",
     "legendFormat": "websockets"
    }
   ]
  },
  {
   "title": "Secure Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(shipreq_webapp_secure_events_total[$__interval]))",
     "legendFormat": "events"
    }
   ]
  },
  {
   "title": "Response Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(shipreq_webapp_http_response_duration_seconds_bucket[$__interval])) by (le))",
     "legendFormat": "http"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(shipreq_webapp_ws_event_duration_seconds_bucket[$__interval])) by (le) + sum(rate(shipreq_webapp_ws_message_duration_seconds_bucket[$__interval])) by (le))",
     "legendFormat": "websocket"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (type) (increase(shipreq_webapp_http_bytes_total[$__interval]))",
     "legendFormat": "http: {{type}}"
    },
    {
     "expr": "sum(increase(shipreq_webapp_ws_bytes_total[$__interval]))",
     "legendFormat": "websockets"
    }
   ]
  }
 ]
}