{
 "title": "Wall (managed)",
 "description": "Meant for wall display",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "time_range", "query": "24h" }
  ]
 },
 "panels": [
  { "title": "Ops", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "EC2s",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count (node_exporter_build_info)"
    }
   ]
  },
  {
   "title": "Uptime: EC2s",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(node_time_seconds - on(instance) node_boot_time_seconds)"
    }
   ]
  },
  {
   "title": "Containers up",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(container_start_time_seconds{ecs_name=~\".+\"}) / sum(ecs_service_desired_tasks)"
    }
   ]
  },
  {
   "title": "Uptime: webapp",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - max(container_start_time_seconds{ecs_name=~\".+-shipreq-webapp\"})"
    }
   ]
  },
  {
   "title": "Uptime: taskman",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - max(container_start_time_seconds{ecs_name=~\".+-shipreq-taskman\"})"
    }
   ]
  },
  {
   "title": "Uptime: others",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - max (container_start_time_seconds{ecs_name!=\"\",ecs_name!~\".+-shipreq-(?:webapp|taskman)\"})"
    }
   ]
  },
  {
   "title": "Secure Events",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(shipreq_webapp_secure_events_total[$time_range]))"
    }
   ]
  },
  {
   "title": "Logs: warnings",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(logback_appender_total{level=~\"[wW].*\"}[$time_range]))"
    }
   ]
  },
  {
   "title": "Logs: errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(logback_appender_total{level=~\"[eEfF].*\"}[$time_range]))"
    }
   ]
  },
  { "title": "Biz", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg_over_time(shipreq_users_total{user_type=\"public\",registered=\"n\"}[$__interval])",
     "legendFormat": "pending users"
    },
    {
     "expr": "avg_over_time(shipreq_users_total{user_type=\"public\",registered=\"y\"}[$__interval])",
     "legendFormat": "registered users"
    },
    {
     "expr": "avg_over_time(shipreq_projects_total{owner_type=\"public\"}[$__interval])",
     "legendFormat": "projects"
    },
    {
     "expr": "avg_over_time(shipreq_events_total{owner_type=\"public\",initial=\"n\"}[$__interval])",
     "legendFormat": "events"
    },
    {
     "expr": "sum (avg_over_time(shipreq_reqs_total{owner_type=\"public\"}[$__interval]))",
     "legendFormat": "reqs"
    }
   ]
  },
  {
   "title": "Unique logins",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 14 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max_over_time(shipreq_daily_logins_total{user_type=\"public\",unique_user=\"y\"}[$time_range])"
    }
   ]
  },
  {
   "title": "WebSockets",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 14 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(max_over_time(shipreq_webapp_ws_open[$time_range]))"
    }
   ]
  },
  {
   "title": "Last login",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 14 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(avg_over_time(shipreq_users_last_login_seconds_ago{user_type=\"public\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Last project write",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 13, "y": 14 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(avg_over_time(shipreq_project_last_access_seconds_ago{owner_type=\"public\",access=\"w\"}[$__interval]))"
    }
   ]
  }
 ]
}