#!/usr/bin/node

// This prunes unnecessary CSS from Semantic UI

const files = { //
  in: 'semantic/dist/semantic.min.css',
  out: 'semantic/dist/semantic.pruned.min.css',
  log: 'semantic/dist/semantic.pruned.log',
  iconsAll: 'shipreq/semantic/icons-all',
  iconsUsed: 'shipreq/semantic/icons-used',
};

const fs = require('fs');

const readLines = filename =>
  fs.readFileSync(filename).toString().split(/\n+/).map(s => s.trim()).filter(s => s != '');

const usedIcons = new Set(readLines(files.iconsUsed));
const unusedIcons = readLines(files.iconsAll).filter(s => !usedIcons.has(s));

const unusedClasses = [
  'mini',
  // 'tiny',
  'small',
  'medium',
  // 'large',
  'big',
  'huge',
  'massive',

  'radio',
  'facebook',
  'twitter',
  'linkedin',
  'youtube',
  'instagram',
  'google',
  'pinterest',
  'vk',

  'vertical',
  'sortable',
  'striped',
  // 'secondary', IN USE - reqtable/ViewsMenu.scala

  // 'two',       IN USE - .ui.form .two.fields
  // 'three',     IN USE - .ui.cards.three
  'four',
  'five',
  'six',
  'seven',
  'eight',
  'nine',
  'ten',
  'eleven',
  'twelve',
  'thirteen',
  'fourteen',
  'fifteen',
  'sixteen',

  // Used colours are in manualRemovals
  'brown',
  'olive',
  'orange',
  'pink',
  'purple',
  'teal',
  'violet',
];

const unusedTransitions = [
  // 'scale', -- used indirectly in ReqTable by popups & modals
  // 'fade', -- used indirectly in ReqTable by popups & modals
  'flip',
  'drop',
  'fly',
  'swing',
  'browse',
  // 'slide', -- used by dropdown component
  'jiggle',
  'flash',
  'shake',
  // 'pulse', -- used in PublicSpa:Login
  'tada',
  'bounce',
];

const manualRemovals = [
  s => /\.inverted/.test(s) && !/\.(?:dimmer|segment|menu)/.test(s),
  s => /\.compact/.test(s) && !/\.(?:table)/.test(s),
  s => /\.black/.test(s) && !/\.(?:button)/.test(s),
  s => /\.blue/.test(s) && !/\.(?:button|card)/.test(s),
  s => /\.green/.test(s) && !/\.(?:button)/.test(s),
  s => /\.grey/.test(s) && !/\.(?:icon)/.test(s),
  s => /\.red/.test(s) && !/\.(?:label|button|icon)/.test(s),
  s => /\.yellow/.test(s) && !/\.(?:card|icon)/.test(s),
];

// █████████████████████████████████████████████████████████████████████████████████████████████████████████████████████

Array.prototype.exists = function(f) {
  return this.findIndex(f) >= 0;
}

Array.prototype.forall = function(f) {
  return !this.exists(b => !f(b));
}

Array.prototype.filterNot = function(f) {
  return this.filter(b => !f(b));
}

Array.prototype.partition = function(f) {
  return [this.filter(f), this.filterNot(f)]; // Lol, "efficiency"?! Never heard of it!
}

// [Regex] => String => Bool
function anyRegexMatcher(regexs) {
  return str => regexs.exists(r => r.test(str));
}

// [String] => String
// eg. ['a', 'b'] => '(?:a|b)'
const regexUnion = a => `(?:${a.join('|')})`

const postcss = require('postcss');

function run() {

  const logCfgColour = { //
    reset: "\033[0m",
    prefixRemove: "\033[31m[remove]\033[31;1m",
    prefixRetain: "\033[30;1m[keep  ]",
    sizeColour: keep => keep ? '\033[33;1m' : '\033[31m',
  };
  const logCfg = { //
    reset: "",
    prefixRemove: "[remove]",
    prefixRetain: "[keep  ]",
    sizeColour: keep => '',
  };

  let logVar = '';

  function log(keep, content, size) {
    const p = keep ? logCfg.prefixRetain : logCfg.prefixRemove;
    const s = logCfg.sizeColour(keep) + ('' + size).padStart(6);
    const c = content.replace(/\s+/g, ' ');
    const l = `${s} ${p} ${c}${logCfg.reset}`;
    logVar += `${l}\n`;
    // console.log(l);
  }

  const descAtRule = rule => `@${rule.name} ${rule.params}`;

  function judge(rule, remove, desc, size) {
    log(!remove, desc, size);
    if (remove)
      rule.remove();
  }

  const notUnused = new RegExp(`: *not *\\( *\\. *${regexUnion(unusedClasses)} *\\)`, 'g');
  const rulePreprocessor = s => s.replace(notUnused, '');

  const prune = postcss.plugin('semantic-ui-prune', function myplugin() {
    return function(css) {

      // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      // Remove all comments
      css.walkComments(comment => {
        judge(comment, true, comment.text, comment.text.length);
      });

      // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      // Remove @rules

      const keyframeMatcher = anyRegexMatcher(unusedTransitions.map(n => new RegExp(n, 'i')))
      css.walkAtRules(rule => {

        let remove = false;
        if (/keyframes$/.test(rule.name)) {
          remove = keyframeMatcher(rule.params);
        }
        //  else if (rule.name == 'media') {
        //   // Wouldn't really remove all media queries...
        //   // But removing *all* of them saves 10,819 bytes...
        //   logRemove(n);
        //   rule.remove();

        const size = rule.toString().length;
        judge(rule, remove, descAtRule(rule), size);
      });

      // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      // Remove rules

      const ruleMatchers = [].concat(manualRemovals);
      ruleMatchers.push(anyRegexMatcher([
        new RegExp(`[" .]${regexUnion(unusedTransitions)}(?:[" .]|$)`),
        new RegExp(`\\.icon${regexUnion(unusedIcons.map(n => n.replace('.', '\\.')))}:`),
        new RegExp(`\\.${regexUnion(unusedClasses)}(?:[^a-zA-Z0-9_-]|$)`),
      ]));
      const ruleMatcher = s => {
        const s2 = s.replace(/: *not *\( *: *(?:first-child|last-child|empty) *\)/gi, '');
        return !/:not/.test(s2) && ruleMatchers.exists(f => f(s2));
      };
      css.walkRules(rule => {
        // rule keys : raws,type,nodes,parent,source,selector,lastEach,indexes
        // console.log(Object.keys(rule.parent))
        // console.log(rule.parent.type)

        rule.selectors = rule.selectors.map(rulePreprocessor);

        let desc = rule.selectors.reduce((a, b) => `${a},${b}`);
        if (rule.parent.type === 'atrule')
          desc = `${descAtRule(rule.parent)} ${desc}`;

        const size = rule.toString().length;
        const [removed, kept] = rule.selectors.partition(ruleMatcher);
        const partial = kept.length > 0 && removed.length > 0;
        const remove = kept.length === 0;

        if (partial) {
          const desc = a => a.join(", ");
          // console.log(`From: ${rule.selectors}\nKeep: ${desc(kept)}\nDrop: ${desc(removed)}\n\n`)
          rule.selectors = kept;
          const size2 = removed.map(s => s.length + 1).reduce((a, b) => a + b) - 1;
          log(false, desc(removed), size2);
          log(true, desc(kept), size - size2);
        } else
          judge(rule, remove, desc, size);

      });

    }
  });

  console.log(`Reading: ${files.in}`);
  const contentIn = fs.readFileSync(files.in);
  const contentOut = postcss(prune()).process(contentIn).css;
  console.log(`Writing   : ${files.out}`);
  fs.writeFileSync(files.out, contentOut);
  console.log(`Logging to: ${files.log}`);
  fs.writeFileSync(files.log, logVar);

  const a = contentIn.length,
    b = contentOut.length,
    s = a - b,
    r = (100 * -s / a).toLocaleString(undefined, { maximumFractionDigits: 4 });
  console.log(`Size      : ${a.toLocaleString()} → ${b.toLocaleString()}`)
  console.log(`Reduction : ${s.toLocaleString()} (${r}%)`)
}

run();
