#!/usr/bin/node

// This prunes unnecessary CSS from Semantic UI

const files = { //
  in: 'semantic/dist/semantic.min.css',
  out: 'shipreq/semantic/pruned.min.css',
  log: 'shipreq/semantic/pruned.log',
  iconsAll: 'shipreq/semantic/icons-all',
  iconsUsed: 'shipreq/semantic/icons-used',
};

//       'compact',
//
//       'three',
//       'four',
//       'five',
//       'six',
//       'seven',
//       'eight',
//       'nine',
//       'ten',
//
//       'inverted',

const fs = require('fs');

const readLines = filename =>
  fs.readFileSync(filename).toString().split(/\n+/).map(s => s.trim()).filter(s => s != '');

const usedIcons = new Set(readLines(files.iconsUsed));
const unusedIcons = readLines(files.iconsAll).filter(s => !usedIcons.has(s));

// TODO Be more specific by combining with component
const unusedColours = [
  // 'black',
  // 'blue',
  'brown',
  // 'green',
  // 'grey',
  'olive',
  'orange',
  'pink',
  'purple',
  // 'red',
  'teal',
  'violet',
  // 'white',
  // 'yellow',
];

const unusedSizes = [
  'mini',
  // 'tiny',
  'small',
  'medium',
  // 'large',
  'big',
  'huge',
  'massive',
];

const unusedMisc = [
  'radio',
];

const unusedTransitions = [
  'scale',
  'fade',
  'flip',
  'drop',
  'fly',
  'swing',
  'browse',
  'slide',
  'jiggle',
  'flash',
  'shake',
  // 'pulse', -- used in PublicSpa:Login
  'tada',
  'bounce',
];

const manualRemovals = [
  s => /\.inverted/.test(s) && !/\.(?:dimmer|segment|menu)/.test(s),
];

// █████████████████████████████████████████████████████████████████████████████████████████████████████████████████████

Array.prototype.exists = function(f) {
  return this.findIndex(f) >= 0;
}

Array.prototype.forall = function(f) {
  return !this.exists(b => !f(b));
}

// [Regex] => String => Bool
function anyRegexMatcher(regexs) {
  return str => regexs.exists(r => r.test(str));
}

const postcss = require('postcss');

function run() {

  const logCfg = { //
    reset: "\033[0m",
    prefixRemove: "\033[31m[remove] \033[31;1m",
    prefixRetain: "\033[30;1m[keep  ] ",
  };

  let logVar = '';

  function log(keep, content) {
    const c = content.replace(/\s+/g, ' ');
    const p = keep ? logCfg.prefixRetain : logCfg.prefixRemove;
    const l = `${p}${c}${logCfg.reset}`;
    logVar += `${l}\n`;
    console.log(l);
  }

  const descAtRule = rule => `@${rule.name} ${rule.params}`;

  function judge(rule, remove, desc) {
    log(!remove, desc);
    if (remove)
      rule.remove();
  }

  const prune = postcss.plugin('semantic-ui-prune', function myplugin() {
    return function(css) {

      // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      // Remove all comments
      css.walkComments(comment => {
        judge(comment, true, comment.text);
      });

      // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      // Remove @rules

      const keyframeMatcher = anyRegexMatcher(unusedTransitions.map(n => new RegExp(n, 'i')))
      css.walkAtRules(rule => {

        if (/keyframes$/.test(rule.name)) {
          const remove = keyframeMatcher(rule.params);
          judge(rule, remove, descAtRule(rule));
        }
        //  else if (rule.name == 'media') {
        //   // Wouldn't really remove all media queries...
        //   // But removing *all* of them saves 10,819 bytes...
        //   logRemove(n);
        //   rule.remove();
        // } else
        //   console.log(`UNKNOWN ATRULE: ${rule.name}`);
      });

      // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      // Remove rules

      const ruleMatchers = [].concat(manualRemovals);
      ruleMatchers.push(anyRegexMatcher(unusedTransitions.map(n => new RegExp(`[" .]${n}(?:[" .]|$)`))));
      ruleMatchers.push(anyRegexMatcher(unusedIcons.map(n => new RegExp(`\\.icon${n.replace('.', '\\.')}(?:[^a-zA-Z]|$)`))));
      ruleMatchers.push(anyRegexMatcher(unusedColours.map(n => new RegExp(`\\.${n}`))));
      ruleMatchers.push(anyRegexMatcher(unusedSizes.map(n => new RegExp(`\\.${n}(?:[^a-zA-Z]|$)`))));
      ruleMatchers.push(anyRegexMatcher(unusedMisc.map(n => new RegExp(`(?:^|[^a-zA-Z])${n}(?:[^a-zA-Z]|$)`))));
      const ruleMatcher = s => !/:not/.test(s) && ruleMatchers.exists(f => f(s));
      css.walkRules(rule => {
        // rule keys : raws,type,nodes,parent,source,selector,lastEach,indexes
        // console.log(Object.keys(rule.parent))
        // console.log(rule.parent.type)
        let desc = rule.selector;
        if (rule.parent.type === 'atrule')
          desc = `${descAtRule(rule.parent)} ${desc}`;
        const remove = rule.selectors.forall(ruleMatcher);
        judge(rule, remove, desc);
      });

    }
  });

  console.log(`Reading: ${files.in}`);
  const contentIn = fs.readFileSync(files.in);
  const contentOut = postcss(prune()).process(contentIn).css;
  console.log(`Writing   : ${files.out}`);
  fs.writeFileSync(files.out, contentOut);
  console.log(`Logging to: ${files.log}`);
  fs.writeFileSync(files.log, logVar);

  const a = contentIn.length,
    b = contentOut.length,
    s = a - b,
    r = (100 * -s / a).toLocaleString(undefined, { maximumFractionDigits: 4 });
  console.log(`Size      : ${a.toLocaleString()} → ${b.toLocaleString()}`)
  console.log(`Reduction : ${s.toLocaleString()} (${r}%)`)
}

run();
