akka {
  loggers = ["akka.event.slf4j.Slf4jLogger"]
  loglevel = "WARNING"
}

akka.actor.deployment {

  /source {
    dispatcher = main
  }

  /manager {
    dispatcher = main
  }

  /workers {
    router = broadcast-pool
    nr-of-instances = 4
  }
}

main {
  type = PinnedDispatcher
  executor = "thread-pool-executor"
}

work {
  type = PinnedDispatcher
  executor = "thread-pool-executor"
  thread-pool-executor {
    core-pool-size-min = 4
    core-pool-size-max = 4
  }
  throughput = 1
}
