global:
  scrape_interval: ${PROMETHEUS_TECH_SCRAPE_INTERVAL}

scrape_configs:

  - job_name: 'prometheus-tech'
    metrics_path: '/prometheus/tech/metrics'
    dns_sd_configs:
      - names: [ '${PROMETHEUS_TECH_HOST}' ]
        type: 'A'
        port: ${PROMETHEUS_TECH_PORT}

  - job_name: 'prometheus-biz'
    metrics_path: '/prometheus/biz/metrics'
    dns_sd_configs:
      - names: [ '${PROMETHEUS_BIZ_HOST}' ]
        type: 'A'
        port: ${PROMETHEUS_BIZ_PORT}

  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100']

  # - job_name: 'cadvisor'
  #   metrics_path: '/cadvisor/metrics'
  #   static_configs:
  #     - targets: ['cadvisor:8080']

  # - job_name: 'webapp-dev'
  #   metrics_path: '/ops/metrics'
  #   static_configs:
  #     - targets: ['webapp:8080']
