global:
  scrape_interval: ${PROMETHEUS_TECH_SCRAPE_INTERVAL}

scrape_configs:

  ##########################################################################
  # Ops cluster

  - job_name: 'node_exporter-ops'
    dns_sd_configs:
      - names: [ '${OPS_HOST}' ]
        type: 'A'
        port: ${OPS_NODE_EXPORTER_PORT}

  - job_name: 'cadvisor-ops'
    metrics_path: '${CADVISOR_PATH}/metrics'
    dns_sd_configs:
      - names: [ '${OPS_HOST}' ]
        type: 'A'
        port: ${OPS_CADVISOR_PORT}
${CADVISOR_RELABEL}

  - job_name: 'ecs_exporter'
    scrape_interval: ${ECS_EXPORTER_SCRAPE_INTERVAL}
    dns_sd_configs:
      - names: [ '${OPS_HOST}' ]
        type: 'A'
        port: ${ECS_EXPORTER_PORT}

  - job_name: 'prometheus-tech'
    metrics_path: '${PROMETHEUS_TECH_PATH}/metrics'
    dns_sd_configs:
      - names: [ '${PROMETHEUS_TECH_HOST}' ]
        type: 'A'
        port: ${PROMETHEUS_TECH_PORT}

  - job_name: 'prometheus-biz'
    metrics_path: '${PROMETHEUS_BIZ_PATH}/metrics'
    dns_sd_configs:
      - names: [ '${PROMETHEUS_BIZ_HOST}' ]
        type: 'A'
        port: ${PROMETHEUS_BIZ_PORT}

  ##########################################################################
  # App cluster

  - job_name: 'node_exporter-app'
    dns_sd_configs:
      - names: [ '${APP_HOST}' ]
        type: 'A'
        port: ${APP_NODE_EXPORTER_PORT}

  - job_name: 'cadvisor-app'
    metrics_path: '${CADVISOR_PATH}/metrics'
    dns_sd_configs:
      - names: [ '${APP_HOST}' ]
        type: 'A'
        port: ${APP_CADVISOR_PORT}
${CADVISOR_RELABEL}

  - job_name: 'shipreq-webapp'
    metrics_path: '/ops/metrics'
    dns_sd_configs:
      - names: [ '${APP_HOST}' ]
        type: 'A'
        port: ${APP_SHIPREQ_WEBAPP_PORT}
