#!/bin/bash

if [ $# -ne 2 ]; then
  echo "Usage: $0 <url or url file> <msg id>"
  exit 1
fi

tmp=/tmp/$(date +%Y%m%d-%H%M%S)
tmp1=$tmp-1
tmp2=$tmp-2

source "$(dirname "$0")/lib.sh" || exit 1
eval_url "$1"
u="$url/diag/msg/$2"

#echo "URL: $u"
curl -kD $tmp2 "$u" >$tmp1 2>/dev/null
perl -pi -e 's/\s+//g; s/,/, /g' $tmp1
perl -pi -e 's/\z/\n/' $tmp1 $tmp2

if [ -z "$(fgrep '200 OK' $tmp2)" ]; then
  # Error
  r=1
elif [ -n "$(egrep '"archived":false' $tmp1)" ]; then
  # Incomplete
  r=rep
else
  # Complete
  r=0
fi

cat $tmp1
rm -f $tmp1 $tmp2
[ $r == rep ] && sleep 1 && exec "$0" "$@"
exit $r
