#!/bin/bash

if [ $# -lt 1 -o $# -gt 2 ]; then
  echo "Usage: $0 <url or url file> [<reps>]"
  exit 1
fi

source "$(dirname "$0")/lib.sh" || exit 1
eval_url "$1"
[ -n "$2" ] && q="?reps=$2"
u="$url/diag/db.csv$q"

echo "URL: $u"
curl -k "$u"

