#!/bin/bash

if [ $# -ne 1 ]; then
  echo "Usage: $0 <url or url file>"
  exit 1
fi

source "$(dirname "$0")/lib.sh" || exit 1
eval_url "$1"
cd_gatling
echo "URL: $url"

JAVA_OPTS="-Dbaseurl=$url" bin/gatling.sh -s StressTest
