#!/bin/bash
cd $(dirname "$0")/..

S=shipreq

tmux -2 new-session -d -s $S \
  && tmux rename-window ctl \
  && tmux split-window -v \
  && tmux select-pane -t 0 \
  && tmux send-keys "script/webapp/run" C-m \
  && tmux select-pane -t 1 \
  && tmux send-keys "script/taskman/run" C-m

#tmux select-window -t $S:0
tmux -2 attach-session -t $S

#tmux new-window -t $S:0 -n 'Logs'
